import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,Check,Clock3,Copy,FileText,Loader2,Mail,MessageSquareText,RefreshCw,Sparkles,Video}from'lucide-react';
import type{AgentWorkflow}from'./agentWorkflowApi';
import{generateCampaignContentPackage,loadLatestCampaignContentPackage,type CampaignContentPackage,type ContentPackagePayload}from'./campaignContentApi';
import type{AgentLocale}from'./types';

interface Props{locale:AgentLocale;workflow:AgentWorkflow|null;onAddAuditLog:(action:string,details:string)=>void;onContinue:()=>void}
type Tab='hooks'|'scripts'|'ads'|'product'|'emails'|'landing'|'creative';
const copy={ar:{title:'حزمة محتوى الحملة',subtitle:'ينشئ Aura حزمة مترابطة من الموجز المعتمد فقط، دون نشر أي محتوى.',generate:'إنشاء الحزمة — 20 رصيداً',regenerate:'إنشاء نسخة جديدة — 20 رصيداً',empty:'لم يتم إنشاء حزمة لهذه الحملة بعد.',brief:'يجب اعتماد موجز الحملة أولاً.',loading:'جاري إنشاء الحزمة المدعومة بالأدلة…',latest:'النسخة الحالية',copied:'تم النسخ',next:'المتابعة إلى التوجيه الإبداعي',tabs:['الخطافات','السيناريوهات','الإعلانات','المنتج','البريد','صفحة الهبوط','الأفكار الإبداعية'],compliance:'ملاحظات المراجعة'},fr:{title:'Pack de contenu de campagne',subtitle:'Aura génère un pack cohérent uniquement depuis le brief approuvé, sans publication.',generate:'Générer — 20 crédits',regenerate:'Nouvelle version — 20 crédits',empty:'Aucun pack généré pour cette campagne.',brief:'Le brief doit être approuvé.',loading:'Génération du pack fondé sur les preuves…',latest:'Version actuelle',copied:'Copié',next:'Continuer vers la direction créative',tabs:['Accroches','Scripts','Publicités','Produit','E-mails','Landing page','Créatifs'],compliance:'Notes de conformité'},en:{title:'Campaign Content Package',subtitle:'Aura generates one coherent package from the approved brief only, without publishing.',generate:'Generate — 20 credits',regenerate:'Generate new version — 20 credits',empty:'No package has been generated for this campaign.',brief:'Approve the Campaign Brief first.',loading:'Generating the evidence-grounded package…',latest:'Current version',copied:'Copied',next:'Continue to Creative Direction',tabs:['Hooks','Scripts','Ads','Product','Emails','Landing page','Creative ideas'],compliance:'Review notes'}};
const tabs:Tab[]=['hooks','scripts','ads','product','emails','landing','creative'];
function Evidence({refs}:{refs:string[]}){return refs.length?<div className="mt-3 flex flex-wrap gap-1.5">{refs.map((ref)=><span key={ref} className="rounded-md border border-emerald-400/20 bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-200">{ref}</span>)}</div>:null;}
function Card({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-2xl border border-white/10 bg-[#11131d] p-5"><h3 className="font-semibold text-white">{title}</h3><div className="mt-3 text-sm leading-7 text-slate-300">{children}</div></article>}
function CopyButton({value,label}:{value:string;label:string}){const[done,setDone]=useState(false);return <button type="button" onClick={()=>{void navigator.clipboard.writeText(value).then(()=>{setDone(true);setTimeout(()=>setDone(false),1200);});}} className="inline-flex items-center gap-1 rounded-lg border border-white/10 px-2.5 py-1.5 text-[11px] text-slate-400 hover:bg-white/5 hover:text-white">{done?<Check className="h-3 w-3"/>:<Copy className="h-3 w-3"/>}{done?label:'Copy'}</button>}
function renderTab(tab:Tab,p:ContentPackagePayload,labels:typeof copy.en){
 if(tab==='hooks')return <div className="grid gap-3 md:grid-cols-2">{p.hooks.map((item,index)=><Card key={`${item.type}-${index}`} title={`${index+1}. ${item.type}`}><p>{item.text}</p><Evidence refs={item.evidenceRefs}/></Card>)}</div>;
 if(tab==='scripts')return <div className="space-y-4">{p.scripts.map((script)=><Card key={`${script.platform}-${script.title}`} title={`${script.title} · ${script.platform} · ${script.durationSeconds}s`}><div className="mb-3 flex justify-end"><CopyButton value={[script.hook,...script.scenes.flatMap((scene)=>[scene.visual,scene.voiceover,scene.onScreenText]),script.cta].join('\n')} label={labels.copied}/></div><p className="font-medium text-indigo-200">{script.hook}</p><ol className="mt-4 space-y-3">{script.scenes.map((scene)=><li key={scene.order} className="rounded-xl border border-white/10 bg-white/[0.03] p-3"><strong className="text-white">{scene.order}. {scene.visual}</strong><p>{scene.voiceover}</p><p className="text-xs text-slate-500">{scene.onScreenText}</p><Evidence refs={scene.evidenceRefs}/></li>)}</ol><p className="mt-4 font-medium text-emerald-200">CTA: {script.cta}</p><Evidence refs={script.evidenceRefs}/></Card>)}</div>;
 if(tab==='ads')return <div className="grid gap-4 lg:grid-cols-2">{p.ads.map((ad,index)=><Card key={`${ad.platform}-${ad.format}-${index}`} title={`${ad.platform} · ${ad.format}`}><div className="mb-2 flex justify-end"><CopyButton value={`${ad.headline}\n\n${ad.primaryText}\n\n${ad.cta}`} label={labels.copied}/></div><strong className="text-white">{ad.headline}</strong><p className="mt-2 whitespace-pre-wrap">{ad.primaryText}</p><p className="mt-2 text-emerald-200">{ad.cta}</p><Evidence refs={ad.evidenceRefs}/></Card>)}</div>;
 if(tab==='product')return <div className="grid gap-4 lg:grid-cols-2"><Card title={p.descriptions.seoTitle}><p>{p.descriptions.seoDescription}</p><hr className="my-4 border-white/10"/><p>{p.descriptions.short}</p><Evidence refs={p.descriptions.evidenceRefs}/></Card><Card title="Long description"><div className="flex justify-end"><CopyButton value={p.descriptions.long} label={labels.copied}/></div><p className="whitespace-pre-wrap">{p.descriptions.long}</p></Card></div>;
 if(tab==='emails')return <div className="space-y-4">{p.emails.map((email,index)=><Card key={`${email.type}-${index}`} title={`${email.type} · ${email.subject}`}><div className="flex justify-end"><CopyButton value={`${email.subject}\n\n${email.body}`} label={labels.copied}/></div><p className="whitespace-pre-wrap">{email.body}</p><Evidence refs={email.evidenceRefs}/></Card>)}</div>;
 if(tab==='landing')return <div className="space-y-4"><Card title={p.landingPage.headline}><p className="text-base text-indigo-200">{p.landingPage.subheadline}</p><ul className="mt-4 list-disc space-y-1 pl-5">{p.landingPage.benefits.map((item)=><li key={item}>{item}</li>)}</ul><p className="mt-4 font-medium text-emerald-200">{p.landingPage.cta}</p><Evidence refs={p.landingPage.evidenceRefs}/></Card><div className="grid gap-4 lg:grid-cols-2"><Card title="Objections">{p.landingPage.objectionResponses.map((item)=><div key={item.objection} className="mb-3"><strong className="text-white">{item.objection}</strong><p>{item.response}</p></div>)}</Card><Card title="FAQ">{p.landingPage.faq.map((item)=><div key={item.question} className="mb-3"><strong className="text-white">{item.question}</strong><p>{item.answer}</p></div>)}</Card></div></div>;
 return <div className="grid gap-4 lg:grid-cols-2"><Card title="Image prompts">{p.creativePrompts.images.map((item,index)=><p key={item} className="mb-3 rounded-xl border border-white/10 bg-white/[0.03] p-3">{index+1}. {item}</p>)}</Card><Card title="Video concepts">{p.creativePrompts.videoConcepts.map((item,index)=><p key={item} className="mb-3 rounded-xl border border-white/10 bg-white/[0.03] p-3">{index+1}. {item}</p>)}</Card></div>;
}
export default function CampaignContentPackageView({locale,workflow,onAddAuditLog,onContinue}:Props){const labels=copy[locale];const[item,setItem]=useState<CampaignContentPackage|null>(null);const[tab,setTab]=useState<Tab>('hooks');const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{if(!workflow)return;const controller=new AbortController();setLoading(true);loadLatestCampaignContentPackage(workflow,controller.signal).then(setItem).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:String(reason))).finally(()=>setLoading(false));return()=>controller.abort();},[workflow?.id]);
 const summary=useMemo(()=>item?`${item.payload.hooks.length} hooks · ${item.payload.scripts.length} scripts · ${item.payload.ads.length} ads`:'', [item]);
 const generate=async()=>{if(!workflow){setError(labels.brief);return;}setLoading(true);setError('');try{const generated=await generateCampaignContentPackage(workflow);setItem(generated);onAddAuditLog('agent.content_package_generated',`Campaign package v${generated.version} generated from approved brief ${generated.briefId}.`);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setLoading(false);}};
 return <section className="space-y-5"><div className="rounded-3xl border border-indigo-400/20 bg-gradient-to-br from-indigo-500/10 via-[#11131d] to-emerald-500/10 p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-3 flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-500/20 text-indigo-200"><Sparkles className="h-5 w-5"/></div><h2 className="text-2xl font-bold text-white">{labels.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{labels.subtitle}</p>{item&&<p className="mt-3 text-xs text-slate-500">{labels.latest} v{item.version} · {summary} · {item.provider}/{item.model} · {item.creditsCharged} credits</p>}</div><button type="button" onClick={()=>void generate()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-500 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-950/40 transition hover:bg-indigo-400 disabled:cursor-not-allowed disabled:opacity-50">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:item?<RefreshCw className="h-4 w-4"/>:<Sparkles className="h-4 w-4"/>}{item?labels.regenerate:labels.generate}</button></div></div>
 {error&&<div className="flex items-start gap-3 rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-100"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/><span>{error}</span></div>}{loading&&!item&&<div className="flex min-h-56 flex-col items-center justify-center rounded-2xl border border-white/10 bg-[#11131d] text-sm text-slate-400"><Loader2 className="mb-3 h-6 w-6 animate-spin text-indigo-300"/>{labels.loading}</div>}{!loading&&!item&&!error&&<div className="rounded-2xl border border-dashed border-white/10 bg-[#11131d] p-10 text-center text-sm text-slate-500">{labels.empty}</div>}
 {item&&<><div className="flex gap-2 overflow-x-auto pb-1">{tabs.map((key,index)=>{const Icon=[MessageSquareText,Video,Sparkles,FileText,Mail,FileText,Sparkles][index];return <button key={key} type="button" onClick={()=>setTab(key)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs transition ${tab===key?'border-indigo-400/40 bg-indigo-400/15 text-indigo-100':'border-white/10 text-slate-400 hover:bg-white/5'}`}><Icon className="h-3.5 w-3.5"/>{labels.tabs[index]}</button>;})}</div>{renderTab(tab,item.payload,labels)}<div className="rounded-2xl border border-amber-400/20 bg-amber-400/10 p-5"><h3 className="flex items-center gap-2 font-semibold text-amber-100"><Clock3 className="h-4 w-4"/>{labels.compliance}</h3><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-amber-100/80">{item.payload.complianceNotes.map((note)=><li key={note}>{note}</li>)}</ul></div><div className="flex justify-end"><button type="button" onClick={onContinue} className="inline-flex items-center gap-2 rounded-xl bg-fuchsia-500 px-5 py-3 text-sm font-semibold text-white hover:bg-fuchsia-400">{labels.next}<ArrowRight className="h-4 w-4"/></button></div></>}
 </section>;
}
