import { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, FileCheck2, LoaderCircle, Save, ShieldCheck } from 'lucide-react';
import type { AgentLocale } from './types';
import type { AgentWorkflow } from './agentWorkflowApi';
import { createCampaignBriefDraft, loadLatestCampaignBrief, updateCampaignBrief, type CampaignBriefFields, type CampaignBriefRecord } from './campaignBriefApi';

interface Props { locale:AgentLocale; workflow:AgentWorkflow|null; onApproved:(brief:CampaignBriefRecord)=>void; onAddAuditLog:(action:string,details:string)=>void }
const empty:CampaignBriefFields={objective:'',targetMarket:'',targetAudience:'',customerProblem:'',valueProposition:'',primaryAngle:'',offer:'',tone:'',keyBenefits:[],objections:[],contentFormats:['short_video','product_image','ad_copy'],creativeDirection:''};
const copy={
 ar:{title:'موجز الحملة الذكي',intro:'راجع استراتيجية الحملة قبل إنشاء النصوص والصور والفيديو. يفصل Aura الحقائق عن الأدلة والمدخلات والمعلومات الناقصة.',objective:'هدف الحملة',market:'السوق المستهدف',audience:'الجمهور المستهدف',problem:'مشكلة العميل',value:'القيمة المقترحة',angle:'الزاوية الرئيسية',offer:'العرض',tone:'نبرة العلامة',benefits:'الفوائد الرئيسية — سطر لكل فائدة',objections:'الاعتراضات — سطر لكل اعتراض',creative:'التوجيه الإبداعي',save:'حفظ مسودة',approve:'اعتماد الموجز',loading:'تحميل الموجز…',required:'اختر منتجاً وابدأ سير عمل Aura أولاً.',evidence:'الأدلة',warnings:'نقاط تحتاج انتباهاً',approved:'تم اعتماد الموجز. سينتقل Aura إلى صناعة المحتوى.',profit:'لا يتم تقييم الربحية دون بيانات التكلفة الكاملة.'},
 fr:{title:'Brief de campagne intelligent',intro:'Validez la stratégie avant de créer textes, images et vidéos. Aura sépare faits, preuves, saisies et données manquantes.',objective:'Objectif',market:'Marché cible',audience:'Audience cible',problem:'Problème client',value:'Proposition de valeur',angle:'Angle principal',offer:'Offre',tone:'Ton de marque',benefits:'Bénéfices — un par ligne',objections:'Objections — une par ligne',creative:'Direction créative',save:'Enregistrer',approve:'Approuver le brief',loading:'Chargement…',required:'Démarrez d’abord un workflow Aura.',evidence:'Preuves',warnings:'Points à vérifier',approved:'Brief approuvé. Aura passe à la création de contenu.',profit:'La rentabilité n’est pas évaluée sans coûts complets.'},
 en:{title:'Intelligent Campaign Brief',intro:'Review the campaign strategy before creating copy, images, and video. Aura separates facts, evidence, user input, and missing information.',objective:'Campaign objective',market:'Target market',audience:'Target audience',problem:'Customer problem',value:'Value proposition',angle:'Primary angle',offer:'Offer',tone:'Brand tone',benefits:'Key benefits — one per line',objections:'Objections — one per line',creative:'Creative direction',save:'Save draft',approve:'Approve brief',loading:'Loading brief…',required:'Start an Aura workflow first.',evidence:'Evidence',warnings:'Needs attention',approved:'Brief approved. Aura will continue to content creation.',profit:'Profitability is not assessed without complete cost inputs.'},
};
function lines(value:string){return value.split('\n').map((item)=>item.trim()).filter(Boolean);}
function joined(value:string[]){return value.join('\n');}
export default function CampaignBriefEditor({locale,workflow,onApproved,onAddAuditLog}:Props){
 const t=copy[locale];const rtl=locale==='ar';const [form,setForm]=useState<CampaignBriefFields>(empty);const [record,setRecord]=useState<CampaignBriefRecord|null>(null);const [loading,setLoading]=useState(Boolean(workflow));const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState(false);
 useEffect(()=>{if(!workflow){setLoading(false);return;}const controller=new AbortController();setLoading(true);loadLatestCampaignBrief(workflow.id,controller.signal).then((item)=>{if(item){setRecord(item);setForm(item.brief);}else setForm({...empty,targetMarket:typeof workflow.marketContext.country==='string'?workflow.marketContext.country:'',creativeDirection:workflow.templateId?`Use Aura template: ${workflow.templateId}`:''});}).catch((reason:unknown)=>{if(!(reason instanceof DOMException&&reason.name==='AbortError'))setError(reason instanceof Error?reason.message:String(reason));}).finally(()=>setLoading(false));return()=>controller.abort();},[workflow?.id]);
 const set=(key:keyof CampaignBriefFields,value:string|string[])=>setForm((current)=>({...current,[key]:value}));
 const persist=async(status:'draft'|'approved')=>{if(!workflow)return;setSaving(true);setError(null);setSuccess(false);try{const next=record?await updateCampaignBrief(workflow.id,record,form,status):await createCampaignBriefDraft(workflow,form);setRecord(next);setForm(next.brief);onAddAuditLog(status==='approved'?'agent.campaign_brief_approved':'agent.campaign_brief_saved',`Campaign brief v${next.version} for workflow ${workflow.id}.`);if(status==='approved'){setSuccess(true);onApproved(next);}}catch(reason:unknown){setError(reason instanceof Error?reason.message:String(reason));}finally{setSaving(false);}};
 if(!workflow)return <div className="rounded-2xl border border-amber-400/20 bg-amber-400/10 p-6 text-sm text-amber-100">{t.required}</div>;
 if(loading)return <div className="flex min-h-56 items-center justify-center gap-2 rounded-2xl border border-white/10 bg-[#11131d] text-slate-400"><LoaderCircle className="h-5 w-5 animate-spin" />{t.loading}</div>;
 const field=(key:keyof CampaignBriefFields,label:string,area=false)=><label><span className="mb-1 block text-xs text-slate-400">{label}</span>{area?<textarea value={String(form[key]||'')} onChange={(e)=>set(key,e.target.value)} rows={3} maxLength={1000} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white"/>:<input value={String(form[key]||'')} onChange={(e)=>set(key,e.target.value)} maxLength={800} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white"/>}</label>;
 return <div dir={rtl?'rtl':'ltr'} className="space-y-6 rounded-3xl border border-white/10 bg-[#11131d] p-5 sm:p-7">
  <div className="flex gap-3"><span className="rounded-xl bg-indigo-500/15 p-3"><FileCheck2 className="h-6 w-6 text-indigo-300"/></span><div><h2 className="text-xl font-bold text-white">{t.title}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-400">{t.intro}</p></div></div>
  {error&&<div className="flex gap-2 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200"><AlertCircle className="h-4 w-4"/>{error}</div>}{success&&<div className="flex gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-sm text-emerald-100"><CheckCircle2 className="h-4 w-4"/>{t.approved}</div>}
  <div className="grid gap-4 md:grid-cols-2">{field('objective',t.objective)}{field('targetMarket',t.market)}{field('targetAudience',t.audience,true)}{field('customerProblem',t.problem,true)}{field('valueProposition',t.value,true)}{field('primaryAngle',t.angle,true)}{field('offer',t.offer,true)}{field('tone',t.tone)}<label><span className="mb-1 block text-xs text-slate-400">{t.benefits}</span><textarea value={joined(form.keyBenefits)} onChange={(e)=>set('keyBenefits',lines(e.target.value))} rows={4} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white"/></label><label><span className="mb-1 block text-xs text-slate-400">{t.objections}</span><textarea value={joined(form.objections)} onChange={(e)=>set('objections',lines(e.target.value))} rows={4} className="w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-sm text-white"/></label><div className="md:col-span-2">{field('creativeDirection',t.creative,true)}</div></div>
  <div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-3 text-xs text-amber-100"><ShieldCheck className="mb-1 h-4 w-4"/>{record?.brief.profitability?.reason||t.profit}</div>
  {record&&<div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="font-semibold text-white">{t.evidence}</h3><div className="mt-3 space-y-2">{record.evidence.map((item)=><div key={item.id} className="rounded-lg border border-white/5 p-2 text-xs"><span className={item.type==='missing'?'text-amber-300':'text-emerald-300'}>{item.type}</span><p className="mt-1 text-slate-300">{item.field}: {item.value}</p><p className="text-slate-500">{item.source}</p></div>)}</div></section><section className="rounded-2xl border border-white/10 bg-black/20 p-4"><h3 className="font-semibold text-white">{t.warnings}</h3><ul className="mt-3 space-y-2 text-xs text-amber-100">{record.warnings.map((item)=><li key={item}>• {item}</li>)}</ul></section></div>}
  <div className="flex flex-wrap justify-end gap-3"><button disabled={saving} onClick={()=>void persist('draft')} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm text-white"><Save className="h-4 w-4"/>{t.save}</button><button disabled={saving} onClick={()=>void persist('approved')} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-emerald-500 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?<LoaderCircle className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}{t.approve}</button></div>
 </div>;
}
