import React,{useEffect,useState}from'react';
import{AlertTriangle,Archive,CheckCircle2,Download,FileJson,FileText,Hash,Loader2,RefreshCw,ShieldCheck}from'lucide-react';
import type{AgentWorkflow}from'./agentWorkflowApi';
import{createCampaignExport,loadLatestCampaignExport,type CampaignExportRecord}from'./campaignExportApi';
import type{AgentLocale}from'./types';
interface Props{locale:AgentLocale;workflow:AgentWorkflow|null;onAddAuditLog:(action:string,details:string)=>void}
const words={ar:{title:'تصدير حزمة الحملة',subtitle:'ينشئ Aura لقطة ثابتة قابلة للتنزيل من الموجز والمحتوى والتوجيه الإبداعي المعتمد، دون نشرها.',create:'إنشاء حزمة التصدير',refresh:'إنشاء نسخة تصدير جديدة',loading:'جاري تجميع الحزمة والتحقق من سلامتها…',empty:'اعتمد التوجيه الإبداعي ثم أنشئ حزمة التصدير.',json:'تنزيل JSON',markdown:'تنزيل Markdown',sources:'إصدارات المصادر',contents:'محتويات الحزمة',integrity:'سلامة الحزمة',safe:'لم يتم نشر أو جدولة أي محتوى.'},fr:{title:'Export de campagne',subtitle:'Aura crée un instantané téléchargeable du brief, du contenu et de la direction approuvée, sans publication.',create:'Créer le pack export',refresh:'Créer une nouvelle version',loading:'Assemblage et vérification du pack…',empty:'Approuvez la direction créative puis créez l’export.',json:'Télécharger JSON',markdown:'Télécharger Markdown',sources:'Versions sources',contents:'Contenu du pack',integrity:'Intégrité',safe:'Aucun contenu n’a été publié ou planifié.'},en:{title:'Campaign Export',subtitle:'Aura creates a downloadable immutable snapshot of the brief, content, and approved direction without publishing it.',create:'Create export package',refresh:'Create new export version',loading:'Assembling and verifying the package…',empty:'Approve Creative Direction, then create the export.',json:'Download JSON',markdown:'Download Markdown',sources:'Source versions',contents:'Package contents',integrity:'Package integrity',safe:'No content was published or scheduled.'}};
function Card({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-2xl border border-white/10 bg-[#11131d] p-5"><h3 className="font-semibold text-white">{title}</h3><div className="mt-3 text-sm leading-7 text-slate-300">{children}</div></article>}
export default function CampaignExportView({locale,workflow,onAddAuditLog}:Props){const copy=words[locale];const[item,setItem]=useState<CampaignExportRecord|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{if(!workflow)return;const controller=new AbortController();setLoading(true);loadLatestCampaignExport(workflow,controller.signal).then(setItem).catch((reason:unknown)=>{if(reason instanceof DOMException&&reason.name==='AbortError')return;setError(reason instanceof Error?reason.message:String(reason));}).finally(()=>setLoading(false));return()=>controller.abort();},[workflow?.id]);
 const create=async()=>{if(!workflow)return;setLoading(true);setError('');try{const next=await createCampaignExport(workflow);setItem(next);onAddAuditLog('agent.campaign_export_created',`Campaign Export v${next.version} created with SHA-256 ${next.sha256}.`);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setLoading(false);}};
 return <section className="space-y-5"><div className="rounded-3xl border border-cyan-400/20 bg-gradient-to-br from-cyan-500/10 via-[#11131d] to-indigo-500/10 p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-3 flex h-11 w-11 items-center justify-center rounded-2xl bg-cyan-500/20 text-cyan-200"><Archive className="h-5 w-5"/></div><h2 className="text-2xl font-bold text-white">{copy.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{copy.subtitle}</p>{item&&<p className="mt-3 text-xs text-slate-500">v{item.version} · {new Date(item.createdAt).toLocaleString()} · {(item.manifest.bundleBytes/1024).toFixed(1)} KiB</p>}</div><button type="button" onClick={()=>void create()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-400 disabled:opacity-50">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:item?<RefreshCw className="h-4 w-4"/>:<Archive className="h-4 w-4"/>}{item?copy.refresh:copy.create}</button></div></div>
 {error&&<div className="flex gap-3 rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-100"><AlertTriangle className="h-4 w-4 shrink-0"/>{error}</div>}{loading&&!item&&<div className="flex min-h-56 flex-col items-center justify-center rounded-2xl border border-white/10 bg-[#11131d] text-sm text-slate-400"><Loader2 className="mb-3 h-6 w-6 animate-spin text-cyan-300"/>{copy.loading}</div>}{!loading&&!item&&!error&&<div className="rounded-2xl border border-dashed border-white/10 bg-[#11131d] p-10 text-center text-sm text-slate-500">{copy.empty}</div>}
 {item&&<><div className="grid gap-4 lg:grid-cols-3"><Card title={copy.sources}><ul><li>Campaign Brief · v{item.manifest.sourceVersions.brief}</li><li>Content Package · v{item.manifest.sourceVersions.contentPackage}</li><li>Creative Direction · v{item.manifest.sourceVersions.creativeDirection}</li></ul></Card><Card title={copy.contents}><div className="flex flex-wrap gap-2">{item.manifest.includes.map((entry)=><span key={entry} className="rounded-lg border border-indigo-400/20 bg-indigo-400/10 px-2 py-1 text-xs text-indigo-200">{entry}</span>)}</div></Card><Card title={copy.integrity}><p className="flex items-center gap-2 text-emerald-200"><CheckCircle2 className="h-4 w-4"/>SHA-256</p><p className="mt-2 break-all font-mono text-[11px] text-slate-400"><Hash className="mr-1 inline h-3 w-3"/>{item.sha256}</p></Card></div><div className="flex flex-wrap gap-3"><a href={item.downloads.json} download className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-white hover:bg-white/10"><FileJson className="h-4 w-4"/>{copy.json}<Download className="h-4 w-4"/></a><a href={item.downloads.markdown} download className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-white hover:bg-white/10"><FileText className="h-4 w-4"/>{copy.markdown}<Download className="h-4 w-4"/></a></div><div className="flex items-center gap-3 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-5 text-sm text-emerald-100"><ShieldCheck className="h-5 w-5 shrink-0"/>{copy.safe}</div></>}
 </section>}
