import React,{useEffect,useState}from'react';
import{AlertTriangle,ArrowRight,CheckCircle2,Clapperboard,Eye,Image,LayoutTemplate,Loader2,Palette,RefreshCw,ShieldCheck,Sparkles}from'lucide-react';
import type{AgentWorkflow}from'./agentWorkflowApi';
import{approveCreativeDirection,generateCreativeDirection,loadLatestCreativeDirection,type CreativeDirectionRecord}from'./creativeDirectionApi';
import type{AgentLocale}from'./types';
interface Props{locale:AgentLocale;workflow:AgentWorkflow|null;onAddAuditLog:(action:string,details:string)=>void;onContinue:()=>void}
type Tab='identity'|'product'|'platforms'|'storyboards'|'prompts'|'production';
const tabs:Tab[]=['identity','product','platforms','storyboards','prompts','production'];
const words={ar:{title:'التوجيه الإبداعي',subtitle:'يحوّل Aura الحزمة المعتمدة إلى نظام بصري وخطة مشاهد قابلة للمراجعة، دون إنشاء وسائط.',generate:'إنشاء التوجيه — 15 رصيداً',regenerate:'إنشاء نسخة جديدة — 15 رصيداً',approve:'اعتماد التوجيه',approved:'تم اعتماد التوجيه',next:'المتابعة إلى تصدير الحملة',loading:'جاري بناء النظام البصري وخطة الإنتاج…',empty:'أنشئ التوجيه الإبداعي بعد حزمة المحتوى.',tabs:['الهوية البصرية','عرض المنتج','المنصات','لوحات المشاهد','موجهات الصور','الإنتاج والوصول'],notes:'ضوابط المراجعة'},fr:{title:'Direction créative',subtitle:'Aura transforme le pack approuvé en système visuel et plan de scènes, sans générer de média.',generate:'Générer — 15 crédits',regenerate:'Nouvelle version — 15 crédits',approve:'Approuver',approved:'Direction approuvée',next:'Continuer vers l’export',loading:'Création du système visuel et du plan de production…',empty:'Générez la direction après le pack de contenu.',tabs:['Identité','Produit','Plateformes','Storyboards','Prompts image','Production & accès'],notes:'Contrôles'},en:{title:'Creative Direction',subtitle:'Aura turns the approved package into a reviewable visual system and scene plan, without generating media.',generate:'Generate — 15 credits',regenerate:'Generate new version — 15 credits',approve:'Approve direction',approved:'Direction approved',next:'Continue to Campaign Export',loading:'Building the visual system and production plan…',empty:'Generate the direction after the Content Package.',tabs:['Visual identity','Product','Platforms','Storyboards','Image prompts','Production & access'],notes:'Review controls'}};
function Box({title,children}:{title:string;children:React.ReactNode}){return <article className="rounded-2xl border border-white/10 bg-[#11131d] p-5"><h3 className="font-semibold text-white">{title}</h3><div className="mt-3 space-y-3 text-sm leading-7 text-slate-300">{children}</div></article>}
function List({items}:{items:string[]}){return <ul className="list-disc space-y-1 pl-5">{items.map((item)=><li key={item}>{item}</li>)}</ul>}
function Evidence({items}:{items:string[]}){return items.length?<div className="flex flex-wrap gap-1.5">{items.map((item)=><span key={item} className="rounded-md border border-emerald-400/20 bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-200">{item}</span>)}</div>:null;}
function Content({tab,item}:{tab:Tab;item:CreativeDirectionRecord}){const d=item.direction;if(tab==='identity')return <div className="grid gap-4 lg:grid-cols-2"><Box title={d.concept}><div className="flex flex-wrap gap-2">{d.visualIdentity.moodKeywords.map((m)=><span key={m} className="rounded-lg bg-indigo-400/10 px-2 py-1 text-xs text-indigo-200">{m}</span>)}</div><p><strong className="text-white">Heading:</strong> {d.visualIdentity.headingStyle}</p><p><strong className="text-white">Body:</strong> {d.visualIdentity.bodyStyle}</p><p>{d.visualIdentity.composition}</p><p>{d.visualIdentity.lighting}</p><List items={d.visualIdentity.textures}/></Box><Box title="Palette"><div className="grid gap-3 sm:grid-cols-2">{d.visualIdentity.palette.map((color)=><div key={color.hex} className="rounded-xl border border-white/10 p-3"><div className="mb-2 h-12 rounded-lg" style={{backgroundColor:color.hex}}/><strong className="text-white">{color.name} · {color.hex}</strong><p className="text-xs text-slate-400">{color.usage}</p></div>)}</div></Box></div>;
 if(tab==='product')return <div className="grid gap-4 lg:grid-cols-2"><Box title="Hero shot"><p>{d.productPresentation.heroShot}</p><h4 className="font-medium text-white">Details</h4><List items={d.productPresentation.detailShots}/><h4 className="font-medium text-white">Lifestyle</h4><List items={d.productPresentation.lifestyleScenes}/></Box><Box title="Do not alter"><List items={d.productPresentation.prohibitedAlterations}/></Box></div>;
 if(tab==='platforms')return <div className="grid gap-4 md:grid-cols-2">{d.platformFrames.map((frame)=><Box key={`${frame.platform}-${frame.aspectRatio}`} title={`${frame.platform} · ${frame.aspectRatio}`}><p>{frame.safeZones}</p><p><strong className="text-white">Text:</strong> {frame.textDensity}</p><p><strong className="text-white">Pacing:</strong> {frame.pacing}</p></Box>)}</div>;
 if(tab==='storyboards')return <div className="space-y-5">{d.storyboards.map((board)=><Box key={`${board.platform}-${board.sourceScriptTitle}`} title={`${board.sourceScriptTitle} · ${board.platform} · ${board.aspectRatio} · ${board.durationSeconds}s`}><ol className="space-y-3">{board.scenes.map((scene)=><li key={scene.order} className="rounded-xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-center justify-between"><strong className="text-white">Scene {scene.order}</strong><span className="text-xs text-indigo-200">{scene.durationSeconds}s</span></div><p>{scene.framing} · {scene.cameraMotion}</p><p>{scene.action}</p><p className="text-slate-400">{scene.lighting}</p><p className="text-indigo-200">{scene.overlayText}</p><p>{scene.voiceover}</p><details className="mt-2"><summary className="cursor-pointer text-xs text-slate-500">Asset prompt</summary><p className="mt-2 text-xs">{scene.assetPrompt}</p></details><Evidence items={scene.evidenceRefs}/></li>)}</ol></Box>)}</div>;
 if(tab==='prompts')return <div className="grid gap-4 lg:grid-cols-2">{d.imagePrompts.map((prompt)=><Box key={prompt.name} title={`${prompt.name} · ${prompt.aspectRatio}`}><p>{prompt.prompt}</p><p className="rounded-lg border border-rose-400/10 bg-rose-400/5 p-3 text-xs text-rose-100/70">Negative: {prompt.negativePrompt}</p><Evidence items={prompt.evidenceRefs}/></Box>)}</div>;
 return <div className="grid gap-4 lg:grid-cols-2"><Box title="Video continuity"><List items={d.videoDirection.continuityRules}/><h4 className="font-medium text-white">Transitions</h4><List items={d.videoDirection.transitions}/><p>{d.videoDirection.audioMood}</p><p>{d.videoDirection.captionStyle}</p></Box><Box title="Accessibility"><p>{d.accessibility.contrastGuidance}</p><p>{d.accessibility.captionGuidance}</p><p>{d.accessibility.altTextTemplate}</p></Box></div>}
export default function CreativeDirectionView({locale,workflow,onAddAuditLog,onContinue}:Props){const copy=words[locale];const[item,setItem]=useState<CreativeDirectionRecord|null>(null);const[tab,setTab]=useState<Tab>('identity');const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{if(!workflow)return;const controller=new AbortController();setLoading(true);loadLatestCreativeDirection(workflow,controller.signal).then(setItem).catch((reason:unknown)=>{if(reason instanceof DOMException&&reason.name==='AbortError')return;setError(reason instanceof Error?reason.message:String(reason));}).finally(()=>setLoading(false));return()=>controller.abort();},[workflow?.id]);
 const generate=async()=>{if(!workflow)return;setLoading(true);setError('');try{const next=await generateCreativeDirection(workflow);setItem(next);onAddAuditLog('agent.creative_direction_generated',`Creative Direction v${next.version} generated from package ${next.contentPackageId}.`);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setLoading(false);}};
 const approve=async()=>{if(!workflow||!item)return;setLoading(true);setError('');try{const next=await approveCreativeDirection(workflow,item);setItem(next);onAddAuditLog('agent.creative_direction_approved',`Creative Direction v${next.version} approved.`);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setLoading(false);}};
 return <section className="space-y-5"><div className="rounded-3xl border border-fuchsia-400/20 bg-gradient-to-br from-fuchsia-500/10 via-[#11131d] to-indigo-500/10 p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-3 flex h-11 w-11 items-center justify-center rounded-2xl bg-fuchsia-500/20 text-fuchsia-200"><Palette className="h-5 w-5"/></div><h2 className="text-2xl font-bold text-white">{copy.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{copy.subtitle}</p>{item&&<p className="mt-3 text-xs text-slate-500">v{item.version} · r{item.revision} · {item.provider}/{item.model} · {item.creditsCharged} credits</p>}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>void generate()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-semibold text-white hover:bg-white/10 disabled:opacity-50">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:item?<RefreshCw className="h-4 w-4"/>:<Sparkles className="h-4 w-4"/>}{item?copy.regenerate:copy.generate}</button>{item&&<button type="button" onClick={()=>void approve()} disabled={loading||item.status==='approved'} className="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-3 text-sm font-semibold text-slate-950 hover:bg-emerald-400 disabled:opacity-60"><CheckCircle2 className="h-4 w-4"/>{item.status==='approved'?copy.approved:copy.approve}</button>}</div></div></div>
 {error&&<div className="flex gap-3 rounded-xl border border-rose-400/20 bg-rose-400/10 p-4 text-sm text-rose-100"><AlertTriangle className="h-4 w-4 shrink-0"/>{error}</div>}{loading&&!item&&<div className="flex min-h-56 flex-col items-center justify-center rounded-2xl border border-white/10 bg-[#11131d] text-sm text-slate-400"><Loader2 className="mb-3 h-6 w-6 animate-spin text-fuchsia-300"/>{copy.loading}</div>}{!loading&&!item&&!error&&<div className="rounded-2xl border border-dashed border-white/10 bg-[#11131d] p-10 text-center text-sm text-slate-500">{copy.empty}</div>}
 {item&&<><div className="flex gap-2 overflow-x-auto">{tabs.map((key,index)=>{const Icon=[Palette,Image,LayoutTemplate,Clapperboard,Sparkles,Eye][index];return <button key={key} type="button" onClick={()=>setTab(key)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs ${tab===key?'border-fuchsia-400/40 bg-fuchsia-400/15 text-fuchsia-100':'border-white/10 text-slate-400 hover:bg-white/5'}`}><Icon className="h-3.5 w-3.5"/>{copy.tabs[index]}</button>})}</div><Content tab={tab} item={item}/><div className="rounded-2xl border border-amber-400/20 bg-amber-400/10 p-5"><h3 className="flex items-center gap-2 font-semibold text-amber-100"><ShieldCheck className="h-4 w-4"/>{copy.notes}</h3><List items={item.direction.complianceNotes}/></div>{item.status==='approved'&&<div className="flex justify-end"><button type="button" onClick={onContinue} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-400">{copy.next}<ArrowRight className="h-4 w-4"/></button></div>}</>}
 </section>}
