import type{AgentWorkflow}from'./agentWorkflowApi';
export type ProductionAssetKind='generated_visual'|'product_reference'|'voiceover';
export interface ProductionAssetSlot{id:string;kind:ProductionAssetKind;required:boolean;status:'planned';prompt:string;negativePrompt?:string;evidenceRefs:string[]}
export interface ProductionLayer{id:string;type:string;zIndex:number;startFrame:number;endFrame:number;assetSlotId?:string;content?:string}
export interface ProductionSceneNode{id:string;order:number;startFrame:number;endFrame:number;durationFrames:number;durationSeconds:number;framing:string;action:string;cameraMotion:string;lighting:string;transitionIn:string;transitionOut:string;layers:ProductionLayer[];assetSlots:ProductionAssetSlot[]}
export interface ProductionRenderTarget{id:string;sourceStoryboardIndex:number;sourceScriptTitle:string;platform:string;aspectRatio:string;width:number;height:number;fps:number;durationFrames:number;durationSeconds:number;safeArea:{top:number;right:number;bottom:number;left:number};scenes:ProductionSceneNode[]}
export interface ProductionBlueprint{schemaVersion:'aurapost.production-blueprint.v1';generatedAt:string;locale:string;creativeDirectionId:string;creativeDirectionVersion:number;renderEngine:'remotion';targets:ProductionRenderTarget[];continuityRules:string[];transitions:string[];audioMood:string;captionStyle:string;accessibility:{contrastGuidance:string;captionGuidance:string;altTextTemplate:string};prohibitedAlterations:string[];complianceNotes:string[];executionPolicy:{mediaGeneration:false;rendering:false;publishing:false;notice:string};contentSha256:string}
export interface ProductionBlueprintRecord{id:string;workflowId:string;briefId:string;contentPackageId:string;creativeDirectionId:string;version:number;revision:number;status:'draft'|'approved';locale:string;blueprint:ProductionBlueprint;sha256:string;createdAt:string;updatedAt:string}
async function request<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,credentials:'include',headers:{Accept:'application/json',...(init?.body?{'Content-Type':'application/json'}:{}),...(init?.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload.error==='string'?payload.error:'Production Blueprint request failed.');return payload as T;}
export async function loadLatestProductionBlueprint(workflow:AgentWorkflow,signal?:AbortSignal):Promise<ProductionBlueprintRecord|null>{const result=await request<{productionBlueprint:ProductionBlueprintRecord|null}>(`/api/agent/workflows/${encodeURIComponent(workflow.id)}/production-blueprints/latest`,{signal});return result.productionBlueprint;}
export async function createProductionBlueprint(workflow:AgentWorkflow):Promise<ProductionBlueprintRecord>{const result=await request<{productionBlueprint:ProductionBlueprintRecord}>(`/api/agent/workflows/${encodeURIComponent(workflow.id)}/production-blueprints`,{method:'POST',headers:{'Idempotency-Key':globalThis.crypto.randomUUID()},body:'{}'});return result.productionBlueprint;}
export async function approveProductionBlueprint(workflow:AgentWorkflow,item:ProductionBlueprintRecord):Promise<ProductionBlueprintRecord>{const result=await request<{productionBlueprint:ProductionBlueprintRecord}>(`/api/agent/workflows/${encodeURIComponent(workflow.id)}/production-blueprints/${encodeURIComponent(item.id)}`,{method:'PATCH',body:JSON.stringify({expectedRevision:item.revision,status:'approved'})});return result.productionBlueprint;}
