import { useMemo, useState, useRef, type ComponentType } from 'react';
import { Boxes, Check, Dumbbell, Film, Gem, Globe2, Home as HomeIcon, Megaphone, Play, Search, Shirt, Sparkles, Users, Utensils } from 'lucide-react';
import type { AgentLocale } from '../agent-shell/types';
import { TEMPLATE_CATEGORIES, SEED_TEMPLATES, filterTemplates, listSubBranches, countByCategory, pickText, type ReadyTemplate, type TemplateCategory, type TemplateCategoryId } from './templateCatalog';

interface Props { locale: AgentLocale; templates?: ReadyTemplate[]; categories?: TemplateCategory[]; selectedTemplateId?: string; onSelect?: (template: ReadyTemplate) => void; onStartPromo?: () => void }
const copy = {
  ar: { title: 'القوالب الجاهزة', subtitle: 'اختر قالبًا حقيقيًا كبداية للفيديو. إذا لم توجد معاينة فيديو، نعرض نموذجًا بصريًا احترافيًا بدل المستطيل الفارغ.', search: 'ابحث عن قالب…', all: 'الكل', use: 'استخدم هذا القالب', selected: 'مختار', two: 'حوار شخصين', noResults: 'لا توجد قوالب مطابقة.', preview: 'نموذج القالب', promoTitle: 'وضع البرو بدون قالب', promoBody: 'صِف فكرتك وسيقود الوكيل الإنتاج بدون قالب ثابت.', promoCta: 'ابدأ برو حر' },
  fr: { title: 'Modèles prêts', subtitle: 'Choisissez un vrai point de départ vidéo. Sans aperçu vidéo, une maquette visuelle remplace le rectangle vide.', search: 'Rechercher un modèle…', all: 'Tout', use: 'Utiliser ce modèle', selected: 'Sélectionné', two: 'Dialogue à deux', noResults: 'Aucun modèle correspondant.', preview: 'Maquette modèle', promoTitle: 'Mode Promo sans modèle', promoBody: 'Décrivez votre idée et l’agent pilote la production.', promoCta: 'Démarrer une promo' },
  en: { title: 'Ready Templates', subtitle: 'Choose a real video starting point. When no preview exists, a professional visual mockup replaces the empty rectangle.', search: 'Search a template…', all: 'All', use: 'Use this template', selected: 'Selected', two: 'Two-person dialogue', noResults: 'No matching templates.', preview: 'Template mockup', promoTitle: 'Promo mode without template', promoBody: 'Describe the idea and the agent drives production.', promoCta: 'Start a free promo' },
} satisfies Record<AgentLocale, Record<string, string>>;
const categoryIcons: Record<TemplateCategoryId, ComponentType<{ className?: string }>> = { jewelry: Gem, fashion: Shirt, beauty: Sparkles, electronics: Boxes, home: HomeIcon, fitness: Dumbbell, food: Utensils, universal: Megaphone };

function TemplateMockup({ template, locale, labels }: { template: ReadyTemplate; locale: AgentLocale; labels: (typeof copy)['en'] }) {
  return <div className={`absolute inset-0 overflow-hidden bg-gradient-to-br ${template.visual?.gradient || template.accent}`}>
    <div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-white/25 blur-2xl" />
    <div className="absolute -bottom-12 -left-8 h-36 w-36 rounded-full bg-black/30 blur-2xl" />
    <div className="relative flex h-full flex-col justify-between p-4 text-white">
      <div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.18em] text-white/75"><span>Aura Template</span><span>{labels.preview}</span></div>
      <div className="text-center"><div className="text-5xl drop-shadow-lg">{template.visual?.emoji || '🎬'}</div><h3 className="mt-3 text-lg font-black leading-tight">{pickText(template.title, locale)}</h3><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-white/75">{pickText(template.scenario.hook, locale)}</p></div>
      <div className="space-y-2">{(template.visual?.frames || template.scenario.scenes).slice(0, 3).map((frame, index) => <div key={index} className="flex items-center gap-2 rounded-full bg-black/25 px-3 py-1.5 text-[10px] font-semibold backdrop-blur"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-white text-[9px] text-zinc-900">{index + 1}</span><span className="truncate">{typeof frame === 'string' ? frame : pickText(frame, locale)}</span></div>)}</div>
    </div>
  </div>;
}

function TemplateCard({ template, locale, active, labels, onSelect }: { template: ReadyTemplate; locale: AgentLocale; active: boolean; labels: (typeof copy)['en']; onSelect?: (template: ReadyTemplate) => void }) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const play = () => { const video = videoRef.current; if (video && template.previewVideoUrl) void video.play().catch(() => undefined); };
  const stop = () => { const video = videoRef.current; if (video) { video.pause(); try { video.currentTime = 0; } catch { /* ignore */ } } };
  return <article onMouseEnter={play} onMouseLeave={stop} className={`group overflow-hidden rounded-3xl border bg-white shadow-sm transition ${active ? 'border-emerald-400 ring-4 ring-emerald-100' : 'border-zinc-200 hover:border-violet-300 hover:shadow-xl'}`}>
    <div className="flex justify-center bg-zinc-100 p-4"><div className="relative aspect-[9/16] w-full max-w-[190px] overflow-hidden rounded-[2rem] border-[6px] border-zinc-950 bg-zinc-950 shadow-2xl"><div className="absolute left-1/2 top-0 z-20 h-5 w-20 -translate-x-1/2 rounded-b-2xl bg-zinc-950" />{template.previewVideoUrl ? <video ref={videoRef} src={template.previewVideoUrl} poster={template.posterUrl || undefined} muted loop playsInline preload="metadata" onFocus={play} onBlur={stop} className="absolute inset-0 h-full w-full object-cover" /> : <TemplateMockup template={template} locale={locale} labels={labels} />}<span className="absolute bottom-2 left-1/2 z-20 -translate-x-1/2 rounded-full bg-black/55 px-2 py-0.5 text-[9px] font-semibold text-white">{template.aspectRatio} · {template.durationSeconds}s</span><span className="absolute right-2 top-7 z-20 rounded-full bg-white/90 p-2 text-zinc-950 shadow"><Play className="h-3.5 w-3.5 fill-current" /></span></div></div>
    <div className="space-y-2 p-4"><h3 className="font-bold text-zinc-950">{pickText(template.title, locale)}</h3><p className="line-clamp-2 text-xs leading-5 text-zinc-500">{pickText(template.description, locale)}</p><div className="flex flex-wrap items-center gap-2 pt-1 text-[10px] text-zinc-500"><span className="inline-flex items-center gap-1 rounded-full border border-zinc-200 px-2 py-0.5"><Globe2 className="h-3 w-3 text-violet-500" />{template.actorLocales.map((code) => code.toUpperCase()).join(' · ')}</span>{template.isTwoPerson && <span className="inline-flex items-center gap-1 rounded-full border border-violet-200 bg-violet-50 px-2 py-0.5 text-violet-700"><Users className="h-3 w-3" />{labels.two}</span>}</div><button type="button" onClick={() => onSelect?.(template)} className={`mt-2 inline-flex w-full items-center justify-center gap-2 rounded-xl px-3 py-2.5 text-xs font-bold transition ${active ? 'bg-emerald-500 text-white' : 'bg-gradient-to-r from-violet-600 to-emerald-500 text-white hover:brightness-110'}`}>{active && <Check className="h-3.5 w-3.5" />}{active ? labels.selected : labels.use}</button></div>
  </article>;
}

export default function ReadyTemplatesGallery({ locale, templates = SEED_TEMPLATES, categories = TEMPLATE_CATEGORIES, selectedTemplateId, onSelect, onStartPromo }: Props) {
  const t = copy[locale]; const rtl = locale === 'ar'; const [activeCategory, setActiveCategory] = useState<TemplateCategoryId | 'all'>('all'); const [activeSub, setActiveSub] = useState<string | 'all'>('all'); const [query, setQuery] = useState('');
  const counts = useMemo(() => countByCategory(templates), [templates]);
  const subBranches = useMemo(() => (activeCategory === 'all' ? [] : listSubBranches(activeCategory, categories)), [activeCategory, categories]);
  const filtered = useMemo(() => filterTemplates(templates, { categoryId: activeCategory, subBranchId: activeSub, query, locale }), [templates, activeCategory, activeSub, query, locale]);
  const selectCategory = (categoryId: TemplateCategoryId | 'all') => { setActiveCategory(categoryId); setActiveSub('all'); };
  return <div dir={rtl ? 'rtl' : 'ltr'} className="space-y-6 text-zinc-950"><div className="flex flex-col gap-4 rounded-3xl border border-violet-100 bg-white/90 p-6 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><span className="rounded-2xl bg-violet-100 p-3"><Film className="h-6 w-6 text-violet-600" /></span><div><h2 className="text-2xl font-black">{t.title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-zinc-500">{t.subtitle}</p></div></div><label className="relative w-full max-w-xs"><Search className="absolute top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400 ltr:left-3 rtl:right-3" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search} className="w-full rounded-2xl border border-zinc-200 bg-zinc-50 py-3 text-sm outline-none focus:border-violet-300 ltr:pl-9 ltr:pr-3 rtl:pr-9 rtl:pl-3" /></label></div>
    {onStartPromo && <div className="flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-amber-500" /><div><p className="text-sm font-bold text-amber-900">{t.promoTitle}</p><p className="mt-1 text-xs text-amber-700">{t.promoBody}</p></div></div><button type="button" onClick={onStartPromo} className="shrink-0 rounded-xl border border-amber-300 bg-white px-4 py-2 text-xs font-bold text-amber-800">{t.promoCta}</button></div>}
    <div className="flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><button type="button" onClick={() => selectCategory('all')} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-bold ${activeCategory === 'all' ? 'border-violet-400 bg-violet-50 text-violet-700' : 'border-zinc-200 bg-white text-zinc-600'}`}>{t.all} · {templates.length}</button>{categories.map((category) => { const Icon = categoryIcons[category.id] ?? Sparkles; const active = activeCategory === category.id; return <button key={category.id} type="button" onClick={() => selectCategory(category.id)} className={`inline-flex shrink-0 items-center gap-2 rounded-full border px-4 py-2 text-xs font-bold ${active ? 'border-violet-400 bg-violet-50 text-violet-700' : 'border-zinc-200 bg-white text-zinc-600'}`}><Icon className="h-3.5 w-3.5" />{pickText(category.label, locale)}<span className="text-zinc-400">{counts[category.id] ?? 0}</span></button>; })}</div>
    {subBranches.length > 0 && <div className="flex flex-wrap gap-2"><button type="button" onClick={() => setActiveSub('all')} className={`rounded-lg border px-3 py-1.5 text-[11px] font-semibold ${activeSub === 'all' ? 'border-emerald-400 bg-emerald-50 text-emerald-700' : 'border-zinc-200 bg-white text-zinc-500'}`}>{t.all}</button>{subBranches.map((sub) => <button key={sub.id} type="button" onClick={() => setActiveSub(sub.id)} className={`rounded-lg border px-3 py-1.5 text-[11px] font-semibold ${activeSub === sub.id ? 'border-emerald-400 bg-emerald-50 text-emerald-700' : 'border-zinc-200 bg-white text-zinc-500'}`}>{pickText(sub.label, locale)}</button>)}</div>}
    {filtered.length === 0 ? <p className="rounded-2xl border border-dashed border-zinc-200 bg-white p-10 text-center text-sm text-zinc-500">{t.noResults}</p> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map((template) => <TemplateCard key={template.id} template={template} locale={locale} active={selectedTemplateId === template.id} labels={t} onSelect={onSelect} />)}</div>}
  </div>;
}
