import crypto from 'node:crypto';
import { AgentContractError,type AgentLocale } from './contracts';
import type{BriefEvidence,CampaignBriefData}from'./campaignBrief';
import type{CampaignContentPackage}from'./campaignContentPackage';
import type{CreativeDirectionData}from'./creativeDirection';

export interface CampaignExportBundle{
 schemaVersion:'aurapost.campaign.v1';generatedAt:string;locale:AgentLocale;
 product:{title:string;description:string|null;vendor:string|null;price:number|null;currency:string|null}|null;
 brief:CampaignBriefData;evidence:BriefEvidence[];warnings:string[];contentPackage:CampaignContentPackage;creativeDirection:CreativeDirectionData;
 releasePolicy:{publishing:false;scheduling:false;socialConnections:false;paidAds:false;smartRepost:false;notice:string};
}
export interface CampaignExportManifest{schemaVersion:'aurapost.export-manifest.v1';generatedAt:string;locale:AgentLocale;sourceVersions:{brief:number;contentPackage:number;creativeDirection:number};formats:Array<'json'|'markdown'>;checksumAlgorithm:'sha256';bundleSha256:string;bundleBytes:number;includes:string[]}
function iso(value:string):string{const parsed=new Date(value);if(Number.isNaN(parsed.valueOf()))throw new AgentContractError('INVALID_CAMPAIGN_EXPORT','generatedAt must be an ISO timestamp.');return parsed.toISOString();}
export function buildCampaignExport(input:{generatedAt:string;locale:AgentLocale;product:CampaignExportBundle['product'];brief:CampaignBriefData;evidence:BriefEvidence[];warnings:string[];contentPackage:CampaignContentPackage;creativeDirection:CreativeDirectionData;versions:{brief:number;contentPackage:number;creativeDirection:number}}):{bundle:CampaignExportBundle;manifest:CampaignExportManifest}{
 const generatedAt=iso(input.generatedAt);const bundle:CampaignExportBundle={schemaVersion:'aurapost.campaign.v1',generatedAt,locale:input.locale,product:input.product,brief:input.brief,evidence:input.evidence,warnings:input.warnings,contentPackage:input.contentPackage,creativeDirection:input.creativeDirection,releasePolicy:{publishing:false,scheduling:false,socialConnections:false,paidAds:false,smartRepost:false,notice:'This export is a reviewable content package. It does not publish, schedule, connect social accounts, buy ads, or trigger Smart Repost.'}};
 const serialized=JSON.stringify(bundle);const bundleBytes=Buffer.byteLength(serialized,'utf8');if(bundleBytes>2*1024*1024)throw new AgentContractError('CAMPAIGN_EXPORT_TOO_LARGE','Campaign export exceeds 2 MiB.');const bundleSha256=crypto.createHash('sha256').update(serialized,'utf8').digest('hex');
 const manifest:CampaignExportManifest={schemaVersion:'aurapost.export-manifest.v1',generatedAt,locale:input.locale,sourceVersions:input.versions,formats:['json','markdown'],checksumAlgorithm:'sha256',bundleSha256,bundleBytes,includes:['product','campaign_brief','evidence','content_package','creative_direction','storyboards','image_prompts','compliance_notes','release_policy']};return{bundle,manifest};
}
function safe(value:unknown):string{return String(value??'').replace(/[\u0000-\u001f\u007f]/g,' ').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('|','\\|').replace(/\s+/g,' ').trim();}
function bullets(items:string[]):string{return items.map((item)=>`- ${safe(item)}`).join('\n')||'- None';}
export function renderCampaignExportMarkdown(manifest:CampaignExportManifest,bundle:CampaignExportBundle):string{const b=bundle.brief,p=bundle.contentPackage,d=bundle.creativeDirection;const lines:string[]=[`# ${safe(p.campaignTitle)}`,'',`Generated: ${manifest.generatedAt}`,`Locale: ${manifest.locale}`,`Bundle SHA-256: \`${manifest.bundleSha256}\``,'','> Reviewable export only. No content was published, scheduled, or submitted to an advertising platform.','','## Product',bundle.product?`**${safe(bundle.product.title)}**\n\n${safe(bundle.product.description)}\n\nVendor: ${safe(bundle.product.vendor)}  \nPrice: ${bundle.product.price??'Not provided'} ${safe(bundle.product.currency)}`:'No saved product attached.','','## Campaign Brief',`- Objective: ${safe(b.objective)}`,`- Market: ${safe(b.targetMarket)}`,`- Audience: ${safe(b.targetAudience)}`,`- Customer problem: ${safe(b.customerProblem)}`,`- Value proposition: ${safe(b.valueProposition)}`,`- Primary angle: ${safe(b.primaryAngle)}`,`- Offer: ${safe(b.offer)}`,`- Tone: ${safe(b.tone)}`,'','### Benefits',bullets(b.keyBenefits),'','### Objections',bullets(b.objections),'','## Evidence',...bundle.evidence.map((item)=>`- **${safe(item.type)} · ${safe(item.field)}:** ${safe(item.value)} — ${safe(item.source)}`),'','## Hooks',...p.hooks.map((item,index)=>`${index+1}. **${safe(item.type)}:** ${safe(item.text)}`),'','## Video Scripts'];
 for(const script of p.scripts){lines.push('',`### ${safe(script.title)} · ${safe(script.platform)} · ${script.durationSeconds}s`,`**Hook:** ${safe(script.hook)}`);for(const scene of script.scenes)lines.push(`- Scene ${scene.order}: ${safe(scene.visual)} — VO: ${safe(scene.voiceover)} — Text: ${safe(scene.onScreenText)}`);lines.push(`**CTA:** ${safe(script.cta)}`);}
 lines.push('','## Ad Copy');for(const ad of p.ads)lines.push('',`### ${safe(ad.platform)} · ${safe(ad.format)}`,`**${safe(ad.headline)}**`,'',safe(ad.primaryText),'',`CTA: ${safe(ad.cta)}`);
 lines.push('','## Product Copy',`### ${safe(p.descriptions.seoTitle)}`,safe(p.descriptions.seoDescription),'',safe(p.descriptions.short),'',p.descriptions.long,'','## Emails');for(const email of p.emails)lines.push('',`### ${safe(email.type)} · ${safe(email.subject)}`,safe(email.body));
 lines.push('','## Landing Page',`# ${safe(p.landingPage.headline)}`,safe(p.landingPage.subheadline),'','### Benefits',bullets(p.landingPage.benefits),'','### Objection Responses',...p.landingPage.objectionResponses.map((item)=>`- **${safe(item.objection)}** — ${safe(item.response)}`),'','### FAQ',...p.landingPage.faq.map((item)=>`- **${safe(item.question)}** — ${safe(item.answer)}`),'',`CTA: ${safe(p.landingPage.cta)}`,'','## Creative Direction',safe(d.concept),'','### Mood',bullets(d.visualIdentity.moodKeywords),'','### Palette',...d.visualIdentity.palette.map((color)=>`- ${safe(color.name)} · \`${safe(color.hex)}\` · ${safe(color.usage)}`),'','### Product Presentation',`Hero: ${safe(d.productPresentation.heroShot)}`,'',bullets([...d.productPresentation.detailShots,...d.productPresentation.lifestyleScenes]),'','### Prohibited Alterations',bullets(d.productPresentation.prohibitedAlterations),'','## Storyboards');
 for(const board of d.storyboards){lines.push('',`### ${safe(board.sourceScriptTitle)} · ${safe(board.platform)} · ${safe(board.aspectRatio)} · ${board.durationSeconds}s`);for(const scene of board.scenes)lines.push(`- Scene ${scene.order} (${scene.durationSeconds}s): ${safe(scene.framing)}; ${safe(scene.action)}; ${safe(scene.cameraMotion)}; ${safe(scene.lighting)}; Overlay: ${safe(scene.overlayText)}; VO: ${safe(scene.voiceover)}; Prompt: ${safe(scene.assetPrompt)}`);}
 lines.push('','## Image Prompts');for(const prompt of d.imagePrompts)lines.push('',`### ${safe(prompt.name)} · ${safe(prompt.aspectRatio)}`,safe(prompt.prompt),'',`Negative: ${safe(prompt.negativePrompt)}`);lines.push('','## Accessibility',`- Contrast: ${safe(d.accessibility.contrastGuidance)}`,`- Captions: ${safe(d.accessibility.captionGuidance)}`,`- Alt text template: ${safe(d.accessibility.altTextTemplate)}`,'','## Compliance Notes',bullets([...bundle.warnings,...p.complianceNotes,...d.complianceNotes]),'','## Release Policy',safe(bundle.releasePolicy.notice),'');return lines.join('\n');}
