import crypto from 'node:crypto';
import { Router, type Request, type Response } from 'express';
import type { Pool } from 'pg';
import { AgentContractError } from './contracts';
import { assertBriefApprovable, buildCampaignBrief, normalizeCampaignBriefDraft, type CampaignBriefData } from './campaignBrief';

const SCHEMA = `
CREATE TABLE IF NOT EXISTS aura_campaign_briefs (
 id TEXT PRIMARY KEY, workflow_id TEXT NOT NULL REFERENCES aura_agent_workflows(id) ON DELETE CASCADE,
 workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 version INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1, is_latest BOOLEAN NOT NULL DEFAULT TRUE,
 status TEXT NOT NULL DEFAULT 'draft', brief JSONB NOT NULL, evidence JSONB NOT NULL, warnings JSONB NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(workflow_id, version)
);
CREATE INDEX IF NOT EXISTS idx_aura_campaign_brief_latest ON aura_campaign_briefs(workflow_id, is_latest, version DESC);
`;
type AuthReq = Request & { workspaceId?: string; user?: { userId?: string } };
type ProductRow = {title:string;description:string|null;vendor:string|null;price:number|null;currency:string|null};
type Row = { id:string; workflow_id:string; version:number; revision:number; status:string; brief:CampaignBriefData; evidence:unknown[]; warnings:string[]; created_at:Date|string; updated_at:Date|string };
function auth(req: AuthReq) { if (!req.workspaceId || !req.user?.userId) throw new AgentContractError('AGENT_AUTH_CONTEXT_MISSING','Authenticated workspace context is required.'); return { workspaceId:req.workspaceId,userId:req.user.userId }; }
function send(res: Response, error: unknown) { if (error instanceof AgentContractError) return res.status(error.code === 'AGENT_AUTH_CONTEXT_MISSING' ? 401 : 400).json({error:error.message,code:error.code}); throw error; }
function output(row: Row) { return { id:row.id, workflowId:row.workflow_id, version:row.version, revision:row.revision, status:row.status, brief:row.brief, evidence:row.evidence||[], warnings:row.warnings||[], createdAt:new Date(row.created_at).toISOString(), updatedAt:new Date(row.updated_at).toISOString() }; }

export function createCampaignBriefRouter(pool: Pool): Router {
 const router=Router(); const ready=pool.query(SCHEMA); router.use(async(_q,_s,n)=>{try{await ready;n();}catch(e){n(e);}});
 router.get('/workflows/:workflowId/briefs/latest', async(req:AuthReq,res)=>{try{const {workspaceId,userId}=auth(req);const r=await pool.query<Row>('SELECT * FROM aura_campaign_briefs WHERE workflow_id=$1 AND workspace_id=$2 AND user_id=$3 AND is_latest=TRUE ORDER BY version DESC LIMIT 1',[req.params.workflowId,workspaceId,userId]);return res.json({brief:r.rows[0]?output(r.rows[0]):null});}catch(e){return send(res,e);}});
 router.post('/workflows/:workflowId/briefs/draft', async(req:AuthReq,res)=>{try{const {workspaceId,userId}=auth(req);const normalized=normalizeCampaignBriefDraft(req.body);const wf=await pool.query<{prompt:string;template_id:string|null;product_id:string|null;market_context:Record<string,unknown>}>('SELECT prompt,template_id,product_id,market_context FROM aura_agent_workflows WHERE id=$1 AND workspace_id=$2 AND user_id=$3 LIMIT 1',[req.params.workflowId,workspaceId,userId]);if(!wf.rows[0])return res.status(404).json({error:'Aura workflow not found.',code:'AGENT_WORKFLOW_NOT_FOUND'});let product:ProductRow|null=null;if(wf.rows[0].product_id){const p=await pool.query<ProductRow>('SELECT title,description,vendor,price,currency FROM products WHERE id=$1 AND workspace_id=$2 LIMIT 1',[wf.rows[0].product_id,workspaceId]);product=p.rows[0]||null;}const built=buildCampaignBrief(normalized,{prompt:wf.rows[0].prompt,templateId:wf.rows[0].template_id,marketContext:wf.rows[0].market_context||{},product});const client=await pool.connect();try{await client.query('BEGIN');const v=await client.query<{next_version:number}>('SELECT COALESCE(MAX(version),0)+1 AS next_version FROM aura_campaign_briefs WHERE workflow_id=$1',[req.params.workflowId]);await client.query('UPDATE aura_campaign_briefs SET is_latest=FALSE WHERE workflow_id=$1',[req.params.workflowId]);const r=await client.query<Row>('INSERT INTO aura_campaign_briefs(id,workflow_id,workspace_id,user_id,version,brief,evidence,warnings) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb) RETURNING *',[crypto.randomUUID(),req.params.workflowId,workspaceId,userId,v.rows[0].next_version,JSON.stringify(built.brief),JSON.stringify(built.evidence),JSON.stringify(built.warnings)]);await client.query('COMMIT');return res.status(201).json({brief:output(r.rows[0])});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}catch(e){return send(res,e);}});
 router.patch('/workflows/:workflowId/briefs/:briefId',async(req:AuthReq,res)=>{try{const {workspaceId,userId}=auth(req);if(!Number.isSafeInteger(req.body?.expectedRevision)||req.body.expectedRevision<1)throw new AgentContractError('INVALID_CAMPAIGN_BRIEF','expectedRevision must be a positive integer.');const status=req.body.status==='approved'?'approved':'draft';const normalized=normalizeCampaignBriefDraft(req.body.brief);const current=await pool.query<Row>('SELECT * FROM aura_campaign_briefs WHERE id=$1 AND workflow_id=$2 AND workspace_id=$3 AND user_id=$4 LIMIT 1',[req.params.briefId,req.params.workflowId,workspaceId,userId]);if(!current.rows[0])return res.status(404).json({error:'Campaign brief not found.',code:'CAMPAIGN_BRIEF_NOT_FOUND'});const next={...current.rows[0].brief,...normalized};if(status==='approved')assertBriefApprovable(next);const r=await pool.query<Row>('UPDATE aura_campaign_briefs SET brief=$6::jsonb,status=$7,revision=revision+1,updated_at=NOW() WHERE id=$1 AND workflow_id=$2 AND workspace_id=$3 AND user_id=$4 AND revision=$5 RETURNING *',[req.params.briefId,req.params.workflowId,workspaceId,userId,req.body.expectedRevision,JSON.stringify(next),status]);if(r.rows[0])return res.json({brief:output(r.rows[0])});return res.status(409).json({error:'Campaign brief changed in another request.',code:'CAMPAIGN_BRIEF_VERSION_CONFLICT'});}catch(e){return send(res,e);}});
 return router;
}
