import crypto from 'crypto';
import { Router, type Request, type Response } from 'express';
import type { Pool } from 'pg';
import { AgentContractError, normalizeIdempotencyKey, type AgentLocale } from './contracts';
import type { BriefEvidence, CampaignBriefData } from './campaignBrief';
import { generateCampaignContentPackage, type CampaignContentPackage } from './campaignContentPackage';

const COST=20;
const SCHEMA=`
CREATE TABLE IF NOT EXISTS aura_campaign_content_packages(
 id TEXT PRIMARY KEY,workflow_id TEXT NOT NULL REFERENCES aura_agent_workflows(id) ON DELETE CASCADE,brief_id TEXT NOT NULL REFERENCES aura_campaign_briefs(id) ON DELETE CASCADE,
 workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 version INTEGER NOT NULL,is_latest BOOLEAN NOT NULL DEFAULT TRUE,status TEXT NOT NULL DEFAULT 'generated',locale TEXT NOT NULL,payload JSONB NOT NULL,
 provider TEXT NOT NULL,model TEXT NOT NULL,prompt_tokens INTEGER,completion_tokens INTEGER,latency_ms INTEGER NOT NULL,credits_charged INTEGER NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(workflow_id,version)
);
CREATE INDEX IF NOT EXISTS idx_aura_content_package_latest ON aura_campaign_content_packages(workflow_id,is_latest,version DESC);
CREATE TABLE IF NOT EXISTS aura_campaign_content_requests(
 id TEXT PRIMARY KEY,workflow_id TEXT NOT NULL REFERENCES aura_agent_workflows(id) ON DELETE CASCADE,brief_id TEXT NOT NULL REFERENCES aura_campaign_briefs(id) ON DELETE CASCADE,
 workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,status TEXT NOT NULL,package_id TEXT,error_message TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(workspace_id,user_id,idempotency_key)
);
`;
type AuthReq=Request&{workspaceId?:string;user?:{userId?:string}};
type BriefRow={id:string;brief:CampaignBriefData;evidence:BriefEvidence[];version:number};
type PackageRow={id:string;workflow_id:string;brief_id:string;version:number;status:string;locale:string;payload:CampaignContentPackage;provider:string;model:string;prompt_tokens:number|null;completion_tokens:number|null;latency_ms:number;credits_charged:number;created_at:Date|string};
function auth(req:AuthReq){if(!req.workspaceId||!req.user?.userId)throw new AgentContractError('AGENT_AUTH_CONTEXT_MISSING','Authenticated workspace context is required.');return{workspaceId:req.workspaceId,userId:req.user.userId};}
function send(res:Response,error:unknown){if(error instanceof AgentContractError){const status=error.code==='AGENT_AUTH_CONTEXT_MISSING'?401:error.code==='INSUFFICIENT_AI_CREDITS'?402:error.code==='CAMPAIGN_BRIEF_REQUIRED'?409:400;return res.status(status).json({error:error.message,code:error.code});}throw error;}
function output(row:PackageRow){return{id:row.id,workflowId:row.workflow_id,briefId:row.brief_id,version:row.version,status:row.status,locale:row.locale,payload:row.payload,provider:row.provider,model:row.model,tokens:{prompt:row.prompt_tokens,completion:row.completion_tokens},latencyMs:row.latency_ms,creditsCharged:row.credits_charged,createdAt:new Date(row.created_at).toISOString()};}
async function loadPackage(pool:Pool,id:string,workspaceId:string,userId:string){const result=await pool.query<PackageRow>('SELECT * FROM aura_campaign_content_packages WHERE id=$1 AND workspace_id=$2 AND user_id=$3 LIMIT 1',[id,workspaceId,userId]);return result.rows[0]||null;}

export function createCampaignContentRouter(pool:Pool):Router{
 const router=Router();const ready=pool.query(SCHEMA);router.use(async(_q,_s,n)=>{try{await ready;n();}catch(e){n(e);}});
 router.get('/workflows/:workflowId/content-packages/latest',async(req:AuthReq,res)=>{try{const{workspaceId,userId}=auth(req);const result=await pool.query<PackageRow>('SELECT * FROM aura_campaign_content_packages WHERE workflow_id=$1 AND workspace_id=$2 AND user_id=$3 AND is_latest=TRUE ORDER BY version DESC LIMIT 1',[req.params.workflowId,workspaceId,userId]);return res.json({contentPackage:result.rows[0]?output(result.rows[0]):null});}catch(e){return send(res,e);}});
 router.post('/workflows/:workflowId/content-packages/generate',async(req:AuthReq,res)=>{let requestId:string|undefined;try{const{workspaceId,userId}=auth(req);const key=normalizeIdempotencyKey(req.header('Idempotency-Key'));if(!key)throw new AgentContractError('IDEMPOTENCY_KEY_REQUIRED','Idempotency-Key is required.');const workflow=await pool.query<{locale:AgentLocale;product_id:string|null}>('SELECT locale,product_id FROM aura_agent_workflows WHERE id=$1 AND workspace_id=$2 AND user_id=$3 LIMIT 1',[req.params.workflowId,workspaceId,userId]);if(!workflow.rows[0])return res.status(404).json({error:'Aura workflow not found.',code:'AGENT_WORKFLOW_NOT_FOUND'});const briefResult=await pool.query<BriefRow>("SELECT id,brief,evidence,version FROM aura_campaign_briefs WHERE workflow_id=$1 AND workspace_id=$2 AND user_id=$3 AND status='approved' AND is_latest=TRUE ORDER BY version DESC LIMIT 1",[req.params.workflowId,workspaceId,userId]);const brief=briefResult.rows[0];if(!brief)throw new AgentContractError('CAMPAIGN_BRIEF_REQUIRED','Approve the latest Campaign Brief before generating content.');const existing=await pool.query<{status:string;package_id:string|null;error_message:string|null}>('SELECT status,package_id,error_message FROM aura_campaign_content_requests WHERE workspace_id=$1 AND user_id=$2 AND idempotency_key=$3 LIMIT 1',[workspaceId,userId,key]);if(existing.rows[0]){if(existing.rows[0].status==='completed'&&existing.rows[0].package_id){const saved=await loadPackage(pool,existing.rows[0].package_id,workspaceId,userId);res.setHeader('Idempotency-Replayed','true');return res.json({contentPackage:saved?output(saved):null});}return res.status(409).json({error:existing.rows[0].error_message||'Content package request is already in progress.',code:existing.rows[0].status==='failed'?'CONTENT_PACKAGE_REQUEST_FAILED':'CONTENT_PACKAGE_IN_PROGRESS'});}
 const balance=await pool.query<{balance:number}>("SELECT balance FROM workspace_credit_pools WHERE workspace_id=$1 AND bucket='ai' LIMIT 1",[workspaceId]);if(!balance.rows[0]||balance.rows[0].balance<COST)throw new AgentContractError('INSUFFICIENT_AI_CREDITS',`This action requires ${COST} AI credits.`);requestId=crypto.randomUUID();const reserved=await pool.query('INSERT INTO aura_campaign_content_requests(id,workflow_id,brief_id,workspace_id,user_id,idempotency_key,status) VALUES($1,$2,$3,$4,$5,$6,\'generating\') ON CONFLICT(workspace_id,user_id,idempotency_key) DO NOTHING RETURNING id',[requestId,req.params.workflowId,brief.id,workspaceId,userId,key]);if(!reserved.rows[0])return res.status(409).json({error:'Content package request is already in progress.',code:'CONTENT_PACKAGE_IN_PROGRESS'});
 let product:Record<string,unknown>|null=null;if(workflow.rows[0].product_id){const productResult=await pool.query<Record<string,unknown>>('SELECT title,description,vendor,price,currency,specifications FROM products WHERE id=$1 AND workspace_id=$2 LIMIT 1',[workflow.rows[0].product_id,workspaceId]);product=productResult.rows[0]||null;}
 const generated=await generateCampaignContentPackage({workspaceId,locale:workflow.rows[0].locale,brief:brief.brief,evidence:brief.evidence||[],product});const client=await pool.connect();try{await client.query('BEGIN');const debit=await client.query<{balance:number}>("UPDATE workspace_credit_pools SET balance=balance-$3,used_this_period=used_this_period+$3,updated_at=NOW() WHERE workspace_id=$1 AND bucket=$2 AND balance >= $3 RETURNING balance",[workspaceId,'ai',COST]);if(!debit.rows[0])throw new AgentContractError('INSUFFICIENT_AI_CREDITS',`This action requires ${COST} AI credits.`);const version=await client.query<{next_version:number}>('SELECT COALESCE(MAX(version),0)+1 AS next_version FROM aura_campaign_content_packages WHERE workflow_id=$1',[req.params.workflowId]);await client.query('UPDATE aura_campaign_content_packages SET is_latest=FALSE WHERE workflow_id=$1',[req.params.workflowId]);const packageId=crypto.randomUUID();const saved=await client.query<PackageRow>('INSERT INTO aura_campaign_content_packages(id,workflow_id,brief_id,workspace_id,user_id,version,locale,payload,provider,model,prompt_tokens,completion_tokens,latency_ms,credits_charged) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12,$13,$14) RETURNING *',[packageId,req.params.workflowId,brief.id,workspaceId,userId,version.rows[0].next_version,workflow.rows[0].locale,JSON.stringify(generated.payload),generated.provider.provider,generated.provider.modelUsed,generated.provider.tokensConsumed?.prompt??null,generated.provider.tokensConsumed?.completion??null,generated.provider.latencyMs,COST]);await client.query('INSERT INTO credit_ledger(id,workspace_id,transaction_type,amount,running_balance,credit_bucket,reference_id,description,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW())',[crypto.randomUUID(),workspaceId,'campaign_content_consume',-COST,debit.rows[0].balance,'ai',packageId,`Generated Campaign Content Package v${version.rows[0].next_version}`]);await client.query("UPDATE aura_campaign_content_requests SET status='completed',package_id=$2,updated_at=NOW() WHERE id=$1",[requestId,packageId]);await client.query('COMMIT');return res.status(201).json({contentPackage:output(saved.rows[0])});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
 }catch(e){if(requestId){const storedMessage=e instanceof AgentContractError?e.message:'Content generation failed.';await pool.query("UPDATE aura_campaign_content_requests SET status='failed',error_message=$2,updated_at=NOW() WHERE id=$1",[requestId,storedMessage]).catch(()=>undefined);}return send(res,e);}});
 return router;
}
