export const AGENT_LOCALES=['ar','fr','en']as const;export const AGENT_SOURCE_MODES=['url','image','saved_product','description','template']as const;export const AGENT_WORKFLOW_STEPS=['import_product','select_product','prepare_assets','campaign_brief','market_analysis','content_generation','creative_direction','production_blueprint','media_generation','video_generation','campaign_export','completed']as const;export const AGENT_WORKFLOW_STATUSES=['active','paused','completed','cancelled']as const;
export type AgentLocale=(typeof AGENT_LOCALES)[number];export type AgentSourceMode=(typeof AGENT_SOURCE_MODES)[number];export type AgentWorkflowStep=(typeof AGENT_WORKFLOW_STEPS)[number];export type AgentWorkflowStatus=(typeof AGENT_WORKFLOW_STATUSES)[number];
export interface AgentWorkflowCreateInput{sourceMode:AgentSourceMode;locale:AgentLocale;prompt:string;templateId?:string;productId?:string}export interface AgentWorkflowPatchInput{expectedVersion:number;prompt?:string;templateId?:string|null;productId?:string|null;locale?:AgentLocale;currentStep?:AgentWorkflowStep;status?:AgentWorkflowStatus;marketContext?:Record<string,unknown>;creativeContext?:Record<string,unknown>}
export class AgentContractError extends Error{constructor(public readonly code:string,message:string){super(message);this.name='AgentContractError';}}
function cleanText(value:unknown,field:string,maxLength:number,required=false):string|undefined{if(value===undefined||value===null){if(required)throw new AgentContractError('INVALID_AGENT_WORKFLOW',`${field} is required.`);return undefined;}if(typeof value!=='string')throw new AgentContractError('INVALID_AGENT_WORKFLOW',`${field} must be a string.`);const cleaned=value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'').trim();if(required&&!cleaned)throw new AgentContractError('INVALID_AGENT_WORKFLOW',`${field} is required.`);if(cleaned.length>maxLength)throw new AgentContractError('INVALID_AGENT_WORKFLOW',`${field} exceeds ${maxLength} characters.`);return cleaned;}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}function boundedContext(value:unknown,field:string):Record<string,unknown>|undefined{if(value===undefined)return undefined;if(!isRecord(value))throw new AgentContractError('INVALID_AGENT_WORKFLOW',`${field} must be an object.`);if(Buffer.byteLength(JSON.stringify(value),'utf8')>32*1024)throw new AgentContractError('INVALID_AGENT_WORKFLOW',`${field} exceeds 32 KiB.`);return value;}
export function initialStepForSource(sourceMode:AgentSourceMode):AgentWorkflowStep{switch(sourceMode){case'url':return'import_product';case'saved_product':return'select_product';case'image':return'prepare_assets';case'description':case'template':return'campaign_brief';}}
export function normalizeAgentWorkflowCreate(value:unknown):AgentWorkflowCreateInput{if(!isRecord(value))throw new AgentContractError('INVALID_AGENT_WORKFLOW','Request body must be an object.');if(!AGENT_SOURCE_MODES.includes(value.sourceMode as AgentSourceMode))throw new AgentContractError('INVALID_AGENT_WORKFLOW','Unsupported sourceMode.');if(!AGENT_LOCALES.includes(value.locale as AgentLocale))throw new AgentContractError('INVALID_AGENT_WORKFLOW','Unsupported locale.');return{sourceMode:value.sourceMode as AgentSourceMode,locale:value.locale as AgentLocale,prompt:cleanText(value.prompt??'','prompt',4000)??'',templateId:cleanText(value.templateId,'templateId',100),productId:cleanText(value.productId,'productId',200)};}
export function normalizeAgentWorkflowPatch(value:unknown):AgentWorkflowPatchInput{if(!isRecord(value))throw new AgentContractError('INVALID_AGENT_WORKFLOW','Request body must be an object.');if(!Number.isSafeInteger(value.expectedVersion)||Number(value.expectedVersion)<1)throw new AgentContractError('INVALID_AGENT_WORKFLOW','expectedVersion must be a positive integer.');if(value.locale!==undefined&&!AGENT_LOCALES.includes(value.locale as AgentLocale))throw new AgentContractError('INVALID_AGENT_WORKFLOW','Unsupported locale.');if(value.currentStep!==undefined&&!AGENT_WORKFLOW_STEPS.includes(value.currentStep as AgentWorkflowStep))throw new AgentContractError('INVALID_AGENT_WORKFLOW','Unsupported currentStep.');if(value.status!==undefined&&!AGENT_WORKFLOW_STATUSES.includes(value.status as AgentWorkflowStatus))throw new AgentContractError('INVALID_AGENT_WORKFLOW','Unsupported status.');return{expectedVersion:Number(value.expectedVersion),prompt:value.prompt===undefined?undefined:(cleanText(value.prompt,'prompt',4000)??''),templateId:value.templateId===null?null:cleanText(value.templateId,'templateId',100),productId:value.productId===null?null:cleanText(value.productId,'productId',200),locale:value.locale as AgentLocale|undefined,currentStep:value.currentStep as AgentWorkflowStep|undefined,status:value.status as AgentWorkflowStatus|undefined,marketContext:boundedContext(value.marketContext,'marketContext'),creativeContext:boundedContext(value.creativeContext,'creativeContext')};}
export function normalizeIdempotencyKey(value:unknown):string|undefined{if(value===undefined)return undefined;return cleanText(value,'Idempotency-Key',200,true);}
