import { AIProviderService, type ProviderResponse } from '../ai/provider';
import { AgentContractError, type AgentLocale } from './contracts';
import type { BriefEvidence } from './campaignBrief';
import type { CampaignContentPackage } from './campaignContentPackage';

export interface CreativePaletteColor{name:string;hex:string;usage:string}
export interface CreativeScene{order:number;durationSeconds:number;framing:string;action:string;cameraMotion:string;lighting:string;overlayText:string;voiceover:string;assetPrompt:string;evidenceRefs:string[]}
export interface CreativeStoryboard{sourceScriptTitle:string;platform:string;aspectRatio:string;durationSeconds:number;scenes:CreativeScene[]}
export interface CreativeDirectionData{
 concept:string;
 visualIdentity:{moodKeywords:string[];palette:CreativePaletteColor[];headingStyle:string;bodyStyle:string;composition:string;lighting:string;textures:string[]};
 productPresentation:{heroShot:string;detailShots:string[];lifestyleScenes:string[];prohibitedAlterations:string[]};
 platformFrames:Array<{platform:string;aspectRatio:string;safeZones:string;textDensity:string;pacing:string}>;
 storyboards:CreativeStoryboard[];
 imagePrompts:Array<{name:string;aspectRatio:string;prompt:string;negativePrompt:string;evidenceRefs:string[]}>;
 videoDirection:{continuityRules:string[];transitions:string[];audioMood:string;captionStyle:string};
 accessibility:{contrastGuidance:string;captionGuidance:string;altTextTemplate:string};
 complianceNotes:string[];
}

function record(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown,field:string,max=2000):string{if(typeof value!=='string')throw new AgentContractError('INVALID_CREATIVE_DIRECTION',`${field} must be text.`);const clean=value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'').trim();if(!clean||clean.length>max)throw new AgentContractError('INVALID_CREATIVE_DIRECTION',`${field} must contain 1-${max} characters.`);return clean;}
function array(value:unknown,field:string,min:number,max:number):unknown[]{if(!Array.isArray(value)||value.length<min||value.length>max)throw new AgentContractError('INVALID_CREATIVE_DIRECTION',`${field} must contain ${min}-${max} items.`);return value;}
function strings(value:unknown,field:string,min:number,max:number,itemMax=800):string[]{return array(value,field,min,max).map((item,index)=>text(item,`${field}[${index}]`,itemMax));}
function refs(value:unknown,field:string,valid:Set<string>):string[]{if(!Array.isArray(value)||value.length>30)throw new AgentContractError('INVALID_CREATIVE_DIRECTION',`${field} must be an evidence reference array.`);return value.map((item,index)=>{const ref=text(item,`${field}[${index}]`,200);if(!valid.has(ref))throw new AgentContractError('INVALID_CREATIVE_DIRECTION',`${field} contains an unknown evidence reference.`);return ref;});}
function aspect(value:unknown,field:string):string{const normalized=text(value,field,10);if(!/^\d{1,2}:\d{1,2}$/.test(normalized))throw new AgentContractError('INVALID_CREATIVE_DIRECTION',`${field} must be an aspect ratio such as 9:16.`);return normalized;}

const riskyClaims=[/\d+(?:\.\d+)?%/g,/\b(?:#\s?1|best[- ]selling|guaranteed|clinically proven|certified|limited stock|free shipping)\b/gi];
function assertCopyGrounded(value:string,evidenceText:string):void{for(const pattern of riskyClaims){pattern.lastIndex=0;for(const match of value.match(pattern)||[]){if(!evidenceText.includes(match.toLowerCase()))throw new AgentContractError('UNGROUNDED_CREATIVE_CLAIM',`Creative copy contains an unsupported claim: ${match}`);}}}

export function normalizeCreativeDirection(value:unknown,evidence:BriefEvidence[]):CreativeDirectionData{
 if(!record(value)||!record(value.visualIdentity)||!record(value.productPresentation)||!record(value.videoDirection)||!record(value.accessibility))throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Creative direction sections are required.');
 const valid=new Set(evidence.filter((item)=>item.type!=='missing').map((item)=>item.id));const evidenceText=evidence.filter((item)=>item.type!=='missing').map((item)=>item.value.toLowerCase()).join(' ');
 const palette=array(value.visualIdentity.palette,'visualIdentity.palette',2,8).map((item,index)=>{if(!record(item))throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Palette color must be an object.');const hex=text(item.hex,`palette[${index}].hex`,7);if(!/^#[0-9a-f]{6}$/i.test(hex))throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Palette colors must use six-digit hex values.');return{name:text(item.name,`palette[${index}].name`,80),hex,usage:text(item.usage,`palette[${index}].usage`,300)};});
 const visualIdentity={moodKeywords:strings(value.visualIdentity.moodKeywords,'visualIdentity.moodKeywords',3,12,100),palette,headingStyle:text(value.visualIdentity.headingStyle,'visualIdentity.headingStyle',500),bodyStyle:text(value.visualIdentity.bodyStyle,'visualIdentity.bodyStyle',500),composition:text(value.visualIdentity.composition,'visualIdentity.composition',1000),lighting:text(value.visualIdentity.lighting,'visualIdentity.lighting',1000),textures:strings(value.visualIdentity.textures,'visualIdentity.textures',1,10,200)};
 const productPresentation={heroShot:text(value.productPresentation.heroShot,'productPresentation.heroShot',1500),detailShots:strings(value.productPresentation.detailShots,'productPresentation.detailShots',2,12,800),lifestyleScenes:strings(value.productPresentation.lifestyleScenes,'productPresentation.lifestyleScenes',2,12,1000),prohibitedAlterations:strings(value.productPresentation.prohibitedAlterations,'productPresentation.prohibitedAlterations',2,12,500)};
 const platformFrames=array(value.platformFrames,'platformFrames',2,8).map((item,index)=>{if(!record(item))throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Platform frame must be an object.');return{platform:text(item.platform,`platformFrames[${index}].platform`,80),aspectRatio:aspect(item.aspectRatio,`platformFrames[${index}].aspectRatio`),safeZones:text(item.safeZones,`platformFrames[${index}].safeZones`,500),textDensity:text(item.textDensity,`platformFrames[${index}].textDensity`,300),pacing:text(item.pacing,`platformFrames[${index}].pacing`,500)};});
 const storyboards=array(value.storyboards,'storyboards',1,6).map((item,index)=>{if(!record(item))throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Storyboard must be an object.');const duration=Number(item.durationSeconds);if(!Number.isInteger(duration)||duration<10||duration>90)throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Storyboard duration must be 10-90 seconds.');const scenes=array(item.scenes,`storyboards[${index}].scenes`,3,12).map((scene,sceneIndex)=>{if(!record(scene))throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Creative scene must be an object.');const sceneDuration=Number(scene.durationSeconds);if(!Number.isInteger(sceneDuration)||sceneDuration<1||sceneDuration>30)throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Scene duration must be 1-30 seconds.');const overlayText=text(scene.overlayText,'scene.overlayText',500);const voiceover=text(scene.voiceover,'scene.voiceover',1200);assertCopyGrounded(`${overlayText} ${voiceover}`,evidenceText);return{order:sceneIndex+1,durationSeconds:sceneDuration,framing:text(scene.framing,'scene.framing',500),action:text(scene.action,'scene.action',800),cameraMotion:text(scene.cameraMotion,'scene.cameraMotion',500),lighting:text(scene.lighting,'scene.lighting',500),overlayText,voiceover,assetPrompt:text(scene.assetPrompt,'scene.assetPrompt',1800),evidenceRefs:refs(scene.evidenceRefs??[],'scene.evidenceRefs',valid)};});const total=scenes.reduce((sum,scene)=>sum+scene.durationSeconds,0);if(Math.abs(total-duration)>2)throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Storyboard scene timing must match the declared duration.');return{sourceScriptTitle:text(item.sourceScriptTitle,'storyboard.sourceScriptTitle',300),platform:text(item.platform,'storyboard.platform',80),aspectRatio:aspect(item.aspectRatio,'storyboard.aspectRatio'),durationSeconds:duration,scenes};});
 const imagePrompts=array(value.imagePrompts,'imagePrompts',3,12).map((item,index)=>{if(!record(item))throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Image prompt must be an object.');return{name:text(item.name,`imagePrompts[${index}].name`,200),aspectRatio:aspect(item.aspectRatio,`imagePrompts[${index}].aspectRatio`),prompt:text(item.prompt,`imagePrompts[${index}].prompt`,2000),negativePrompt:text(item.negativePrompt,`imagePrompts[${index}].negativePrompt`,1000),evidenceRefs:refs(item.evidenceRefs??[],`imagePrompts[${index}].evidenceRefs`,valid)};});
 const videoDirection={continuityRules:strings(value.videoDirection.continuityRules,'videoDirection.continuityRules',3,12,600),transitions:strings(value.videoDirection.transitions,'videoDirection.transitions',2,10,400),audioMood:text(value.videoDirection.audioMood,'videoDirection.audioMood',500),captionStyle:text(value.videoDirection.captionStyle,'videoDirection.captionStyle',500)};
 const accessibility={contrastGuidance:text(value.accessibility.contrastGuidance,'accessibility.contrastGuidance',500),captionGuidance:text(value.accessibility.captionGuidance,'accessibility.captionGuidance',500),altTextTemplate:text(value.accessibility.altTextTemplate,'accessibility.altTextTemplate',800)};
 const direction={concept:text(value.concept,'concept',1200),visualIdentity,productPresentation,platformFrames,storyboards,imagePrompts,videoDirection,accessibility,complianceNotes:strings(value.complianceNotes,'complianceNotes',2,20,600)};
 if(Buffer.byteLength(JSON.stringify(direction),'utf8')>256*1024)throw new AgentContractError('INVALID_CREATIVE_DIRECTION','Creative direction exceeds 256 KiB.');return direction;
}
export function assertCreativeDirectionApprovable(direction:CreativeDirectionData):void{if(!direction.concept||direction.visualIdentity.palette.length<2||!direction.productPresentation.heroShot||!direction.storyboards.length||direction.imagePrompts.length<3)throw new AgentContractError('CREATIVE_DIRECTION_INCOMPLETE','Creative direction is incomplete.');}

const schema=`{"concept":"...","visualIdentity":{"moodKeywords":["..."],"palette":[{"name":"...","hex":"#112233","usage":"..."}],"headingStyle":"...","bodyStyle":"...","composition":"...","lighting":"...","textures":["..."]},"productPresentation":{"heroShot":"...","detailShots":["..."],"lifestyleScenes":["..."],"prohibitedAlterations":["..."]},"platformFrames":[{"platform":"...","aspectRatio":"9:16","safeZones":"...","textDensity":"...","pacing":"..."}],"storyboards":[{"sourceScriptTitle":"...","platform":"...","aspectRatio":"9:16","durationSeconds":30,"scenes":[{"durationSeconds":5,"framing":"...","action":"...","cameraMotion":"...","lighting":"...","overlayText":"...","voiceover":"...","assetPrompt":"...","evidenceRefs":[]}]}],"imagePrompts":[{"name":"...","aspectRatio":"1:1","prompt":"...","negativePrompt":"...","evidenceRefs":[]}],"videoDirection":{"continuityRules":["..."],"transitions":["..."],"audioMood":"...","captionStyle":"..."},"accessibility":{"contrastGuidance":"...","captionGuidance":"...","altTextTemplate":"..."},"complianceNotes":["..."]}`;
export async function generateCreativeDirection(input:{workspaceId:string;locale:AgentLocale;contentPackage:CampaignContentPackage;evidence:BriefEvidence[]}):Promise<{direction:CreativeDirectionData;provider:ProviderResponse}>{
 const language=input.locale==='ar'?'Arabic':input.locale==='fr'?'French':'English';const usable=input.evidence.filter((item)=>item.type!=='missing');
 const prompt=`Create a production-ready Creative Direction in ${language}.\nAPPROVED CONTENT PACKAGE:\n${JSON.stringify(input.contentPackage)}\nALLOWED EVIDENCE:\n${JSON.stringify(usable)}\nRules: preserve the product exactly; do not invent materials, colors, dimensions, logos, certifications, results, reviews, offers, scarcity, shipping, or performance. Do not generate images or videos and do not claim anything was published. Storyboard timings must sum to each declared duration within two seconds. Use only supplied evidence IDs. Return strict JSON only.`;
 const provider=await AIProviderService.generateJSON(prompt,'You are Aura, an evidence-grounded creative director for ecommerce production. Convert approved campaign copy into a precise, accessible visual system and scene plan without altering product facts.',schema,{workflow:'advanced_reasoning',temperature:0.2,allowFallbacks:true},input.workspaceId);
 if(!provider.rawContent.trim())throw new AgentContractError('CREATIVE_PROVIDER_EMPTY','AI provider returned empty creative direction.');const parsed=AIProviderService.cleanAndParseJSON<unknown>(provider.rawContent);return{direction:normalizeCreativeDirection(parsed,input.evidence),provider};
}
