import crypto from 'crypto';
import { Router,type Request,type Response } from 'express';
import type{Pool}from'pg';
import{AgentContractError,normalizeIdempotencyKey,type AgentLocale}from'./contracts';
import type{BriefEvidence}from'./campaignBrief';
import type{CampaignContentPackage}from'./campaignContentPackage';
import{assertCreativeDirectionApprovable,generateCreativeDirection,type CreativeDirectionData}from'./creativeDirection';

const COST=15;
const SCHEMA=`
CREATE TABLE IF NOT EXISTS aura_creative_directions(
 id TEXT PRIMARY KEY,workflow_id TEXT NOT NULL,brief_id TEXT NOT NULL,content_package_id TEXT NOT NULL,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,
 version INTEGER NOT NULL,revision INTEGER NOT NULL DEFAULT 1,is_latest BOOLEAN NOT NULL DEFAULT TRUE,status TEXT NOT NULL DEFAULT 'draft',locale TEXT NOT NULL,direction JSONB NOT NULL,
 provider TEXT NOT NULL,model TEXT NOT NULL,prompt_tokens INTEGER,completion_tokens INTEGER,latency_ms INTEGER NOT NULL,credits_charged INTEGER NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(workflow_id,version)
);
CREATE INDEX IF NOT EXISTS idx_aura_creative_direction_latest ON aura_creative_directions(workflow_id,is_latest,version DESC);
CREATE TABLE IF NOT EXISTS aura_creative_direction_requests(
 id TEXT PRIMARY KEY,workflow_id TEXT NOT NULL,brief_id TEXT NOT NULL,content_package_id TEXT NOT NULL,workspace_id TEXT NOT NULL,user_id TEXT NOT NULL,
 idempotency_key TEXT NOT NULL,status TEXT NOT NULL,direction_id TEXT,error_message TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(workspace_id,user_id,idempotency_key)
);`;
type AuthReq=Request&{workspaceId?:string;user?:{userId?:string}};
type PackageRow={id:string;brief_id:string;locale:AgentLocale;payload:CampaignContentPackage};
type DirectionRow={id:string;workflow_id:string;brief_id:string;content_package_id:string;version:number;revision:number;status:string;locale:string;direction:CreativeDirectionData;provider:string;model:string;prompt_tokens:number|null;completion_tokens:number|null;latency_ms:number;credits_charged:number;created_at:Date|string;updated_at:Date|string};
function auth(req:AuthReq){if(!req.workspaceId||!req.user?.userId)throw new AgentContractError('AGENT_AUTH_CONTEXT_MISSING','Authenticated workspace context is required.');return{workspaceId:req.workspaceId,userId:req.user.userId};}
function send(res:Response,error:unknown){if(error instanceof AgentContractError){const status=error.code==='AGENT_AUTH_CONTEXT_MISSING'?401:error.code==='INSUFFICIENT_AI_CREDITS'?402:error.code==='CONTENT_PACKAGE_REQUIRED'?409:400;return res.status(status).json({error:error.message,code:error.code});}throw error;}
function output(row:DirectionRow){return{id:row.id,workflowId:row.workflow_id,briefId:row.brief_id,contentPackageId:row.content_package_id,version:row.version,revision:row.revision,status:row.status,locale:row.locale,direction:row.direction,provider:row.provider,model:row.model,tokens:{prompt:row.prompt_tokens,completion:row.completion_tokens},latencyMs:row.latency_ms,creditsCharged:row.credits_charged,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()};}
async function loadDirection(pool:Pool,id:string,workspaceId:string,userId:string){const result=await pool.query<DirectionRow>('SELECT * FROM aura_creative_directions WHERE id=$1 AND workspace_id=$2 AND user_id=$3 LIMIT 1',[id,workspaceId,userId]);return result.rows[0]||null;}

export function createCreativeDirectionRouter(pool:Pool):Router{const router=Router();const ready=pool.query(SCHEMA);router.use(async(_q,_s,n)=>{try{await ready;n();}catch(e){n(e);}});
 router.get('/workflows/:workflowId/creative-directions/latest',async(req:AuthReq,res)=>{try{const{workspaceId,userId}=auth(req);const result=await pool.query<DirectionRow>('SELECT * FROM aura_creative_directions WHERE workflow_id=$1 AND workspace_id=$2 AND user_id=$3 AND is_latest=TRUE ORDER BY version DESC LIMIT 1',[req.params.workflowId,workspaceId,userId]);return res.json({creativeDirection:result.rows[0]?output(result.rows[0]):null});}catch(e){return send(res,e);}});
 router.post('/workflows/:workflowId/creative-directions/generate',async(req:AuthReq,res)=>{let requestId:string|undefined;try{const{workspaceId,userId}=auth(req);const key=normalizeIdempotencyKey(req.header('Idempotency-Key'));if(!key)throw new AgentContractError('IDEMPOTENCY_KEY_REQUIRED','Idempotency-Key is required.');const workflow=await pool.query<{locale:AgentLocale}>('SELECT locale FROM aura_agent_workflows WHERE id=$1 AND workspace_id=$2 AND user_id=$3 LIMIT 1',[req.params.workflowId,workspaceId,userId]);if(!workflow.rows[0])return res.status(404).json({error:'Aura workflow not found.',code:'AGENT_WORKFLOW_NOT_FOUND'});const packageResult=await pool.query<PackageRow>('SELECT id,brief_id,locale,payload FROM aura_campaign_content_packages WHERE workflow_id=$1 AND workspace_id=$2 AND user_id=$3 AND is_latest=TRUE ORDER BY version DESC LIMIT 1',[req.params.workflowId,workspaceId,userId]);const contentPackage=packageResult.rows[0];if(!contentPackage)throw new AgentContractError('CONTENT_PACKAGE_REQUIRED','Generate the Campaign Content Package before Creative Direction.');const briefResult=await pool.query<{evidence:BriefEvidence[]}>("SELECT evidence FROM aura_campaign_briefs WHERE id=$1 AND workflow_id=$2 AND workspace_id=$3 AND user_id=$4 AND status='approved' LIMIT 1",[contentPackage.brief_id,req.params.workflowId,workspaceId,userId]);if(!briefResult.rows[0])throw new AgentContractError('CONTENT_PACKAGE_REQUIRED','The source Campaign Brief is no longer approved.');const existing=await pool.query<{status:string;direction_id:string|null;error_message:string|null}>('SELECT status,direction_id,error_message FROM aura_creative_direction_requests WHERE workspace_id=$1 AND user_id=$2 AND idempotency_key=$3 LIMIT 1',[workspaceId,userId,key]);if(existing.rows[0]){if(existing.rows[0].status==='completed'&&existing.rows[0].direction_id){const saved=await loadDirection(pool,existing.rows[0].direction_id,workspaceId,userId);res.setHeader('Idempotency-Replayed','true');return res.json({creativeDirection:saved?output(saved):null});}return res.status(409).json({error:existing.rows[0].error_message||'Creative Direction request is already in progress.',code:existing.rows[0].status==='failed'?'CREATIVE_DIRECTION_REQUEST_FAILED':'CREATIVE_DIRECTION_IN_PROGRESS'});}
 const balance=await pool.query<{balance:number}>("SELECT balance FROM workspace_credit_pools WHERE workspace_id=$1 AND bucket='ai' LIMIT 1",[workspaceId]);if(!balance.rows[0]||balance.rows[0].balance<COST)throw new AgentContractError('INSUFFICIENT_AI_CREDITS',`This action requires ${COST} AI credits.`);requestId=crypto.randomUUID();const reserved=await pool.query("INSERT INTO aura_creative_direction_requests(id,workflow_id,brief_id,content_package_id,workspace_id,user_id,idempotency_key,status) VALUES($1,$2,$3,$4,$5,$6,$7,'generating') ON CONFLICT(workspace_id,user_id,idempotency_key) DO NOTHING RETURNING id",[requestId,req.params.workflowId,contentPackage.brief_id,contentPackage.id,workspaceId,userId,key]);if(!reserved.rows[0])return res.status(409).json({error:'Creative Direction request is already in progress.',code:'CREATIVE_DIRECTION_IN_PROGRESS'});
 const generated=await generateCreativeDirection({workspaceId,locale:workflow.rows[0].locale,contentPackage:contentPackage.payload,evidence:briefResult.rows[0].evidence||[]});const client=await pool.connect();try{await client.query('BEGIN');const debit=await client.query<{balance:number}>("UPDATE workspace_credit_pools SET balance=balance-$3,used_this_period=used_this_period+$3,updated_at=NOW() WHERE workspace_id=$1 AND bucket=$2 AND balance >= $3 RETURNING balance",[workspaceId,'ai',COST]);if(!debit.rows[0])throw new AgentContractError('INSUFFICIENT_AI_CREDITS',`This action requires ${COST} AI credits.`);const version=await client.query<{next_version:number}>('SELECT COALESCE(MAX(version),0)+1 AS next_version FROM aura_creative_directions WHERE workflow_id=$1',[req.params.workflowId]);await client.query('UPDATE aura_creative_directions SET is_latest=FALSE WHERE workflow_id=$1',[req.params.workflowId]);const directionId=crypto.randomUUID();const saved=await client.query<DirectionRow>('INSERT INTO aura_creative_directions(id,workflow_id,brief_id,content_package_id,workspace_id,user_id,version,locale,direction,provider,model,prompt_tokens,completion_tokens,latency_ms,credits_charged) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13,$14,$15) RETURNING *',[directionId,req.params.workflowId,contentPackage.brief_id,contentPackage.id,workspaceId,userId,version.rows[0].next_version,workflow.rows[0].locale,JSON.stringify(generated.direction),generated.provider.provider,generated.provider.modelUsed,generated.provider.tokensConsumed?.prompt??null,generated.provider.tokensConsumed?.completion??null,generated.provider.latencyMs,COST]);await client.query('INSERT INTO credit_ledger(id,workspace_id,transaction_type,amount,running_balance,credit_bucket,reference_id,description,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW())',[crypto.randomUUID(),workspaceId,'creative_direction_consume',-COST,debit.rows[0].balance,'ai',directionId,`Generated Creative Direction v${version.rows[0].next_version}`]);await client.query("UPDATE aura_creative_direction_requests SET status='completed',direction_id=$2,updated_at=NOW() WHERE id=$1",[requestId,directionId]);await client.query('COMMIT');return res.status(201).json({creativeDirection:output(saved.rows[0])});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
 }catch(e){if(requestId){const stored=e instanceof AgentContractError?e.message:'Creative Direction generation failed.';await pool.query("UPDATE aura_creative_direction_requests SET status='failed',error_message=$2,updated_at=NOW() WHERE id=$1",[requestId,stored]).catch(()=>undefined);}return send(res,e);}});
 router.patch('/workflows/:workflowId/creative-directions/:directionId',async(req:AuthReq,res)=>{try{const{workspaceId,userId}=auth(req);if(!Number.isSafeInteger(req.body?.expectedRevision)||req.body.expectedRevision<1)throw new AgentContractError('INVALID_CREATIVE_DIRECTION','expectedRevision must be a positive integer.');const status=req.body?.status==='approved'?'approved':'draft';const current=await pool.query<DirectionRow>('SELECT * FROM aura_creative_directions WHERE id=$1 AND workflow_id=$2 AND workspace_id=$3 AND user_id=$4 LIMIT 1',[req.params.directionId,req.params.workflowId,workspaceId,userId]);if(!current.rows[0])return res.status(404).json({error:'Creative Direction not found.',code:'CREATIVE_DIRECTION_NOT_FOUND'});if(status==='approved')assertCreativeDirectionApprovable(current.rows[0].direction);const updated=await pool.query<DirectionRow>('UPDATE aura_creative_directions SET status=$6,revision=revision+1,updated_at=NOW() WHERE id=$1 AND workflow_id=$2 AND workspace_id=$3 AND user_id=$4 AND revision=$5 RETURNING *',[req.params.directionId,req.params.workflowId,workspaceId,userId,req.body.expectedRevision,status]);if(updated.rows[0])return res.json({creativeDirection:output(updated.rows[0])});return res.status(409).json({error:'Creative Direction changed in another request.',code:'CREATIVE_DIRECTION_VERSION_CONFLICT'});}catch(e){return send(res,e);}});
 return router;}
