import crypto from 'crypto';
import { AgentContractError,type AgentLocale } from './contracts';
import type{CreativeDirectionData,CreativeScene,CreativeStoryboard}from'./creativeDirection';

export const PRODUCTION_FPS=30;
export type ProductionLayerType='background'|'generated_visual'|'product'|'overlay_text'|'captions'|'voiceover';
export type ProductionAssetKind='generated_visual'|'product_reference'|'voiceover';
export interface ProductionAssetSlot{id:string;kind:ProductionAssetKind;required:boolean;status:'planned';prompt:string;negativePrompt?:string;evidenceRefs:string[]}
export interface ProductionLayer{id:string;type:ProductionLayerType;zIndex:number;startFrame:number;endFrame:number;assetSlotId?:string;content?:string}
export interface ProductionSceneNode{id:string;order:number;startFrame:number;endFrame:number;durationFrames:number;durationSeconds:number;framing:string;action:string;cameraMotion:string;lighting:string;transitionIn:string;transitionOut:string;layers:ProductionLayer[];assetSlots:ProductionAssetSlot[]}
export interface ProductionRenderTarget{id:string;sourceStoryboardIndex:number;sourceScriptTitle:string;platform:string;aspectRatio:string;width:number;height:number;fps:number;durationFrames:number;durationSeconds:number;safeArea:{top:number;right:number;bottom:number;left:number};scenes:ProductionSceneNode[]}
export interface ProductionBlueprint{schemaVersion:'aurapost.production-blueprint.v1';generatedAt:string;locale:AgentLocale;creativeDirectionId:string;creativeDirectionVersion:number;renderEngine:'remotion';targets:ProductionRenderTarget[];continuityRules:string[];transitions:string[];audioMood:string;captionStyle:string;accessibility:{contrastGuidance:string;captionGuidance:string;altTextTemplate:string};prohibitedAlterations:string[];complianceNotes:string[];executionPolicy:{mediaGeneration:false;rendering:false;publishing:false;notice:string};contentSha256:string}

const DIMENSIONS:Record<string,{width:number;height:number;safeArea:ProductionRenderTarget['safeArea']}>= {
 '9:16':{width:1080,height:1920,safeArea:{top:180,right:90,bottom:300,left:90}},
 '16:9':{width:1920,height:1080,safeArea:{top:72,right:120,bottom:96,left:120}},
 '1:1':{width:1080,height:1080,safeArea:{top:90,right:90,bottom:120,left:90}},
 '4:5':{width:1080,height:1350,safeArea:{top:110,right:90,bottom:170,left:90}},
};
function cleanTimestamp(value:string):string{const parsed=new Date(value);if(Number.isNaN(parsed.valueOf()))throw new AgentContractError('INVALID_PRODUCTION_BLUEPRINT','generatedAt must be an ISO timestamp.');return parsed.toISOString();}
function assetPrompt(scene:CreativeScene):string{return `${scene.assetPrompt}. Framing: ${scene.framing}. Action: ${scene.action}. Camera: ${scene.cameraMotion}. Lighting: ${scene.lighting}. Preserve the approved product exactly.`;}
function compileScene(input:{scene:CreativeScene;sceneIndex:number;targetIndex:number;startFrame:number;durationFrames:number;negativePrompt:string;transitionIn:string;transitionOut:string}):ProductionSceneNode{
 const{scene,sceneIndex,targetIndex,startFrame,durationFrames}=input;const endFrame=startFrame+durationFrames;const base=`target-${String(targetIndex+1).padStart(2,'0')}-scene-${String(sceneIndex+1).padStart(2,'0')}`;const visual=`${base}-visual`;const product=`${base}-product`;const voice=`${base}-voice`;
 const assetSlots:ProductionAssetSlot[]=[{id:visual,kind:'generated_visual',required:true,status:'planned',prompt:assetPrompt(scene),negativePrompt:input.negativePrompt,evidenceRefs:[...scene.evidenceRefs]},{id:product,kind:'product_reference',required:false,status:'planned',prompt:'Use an approved product reference asset when available. Never alter product geometry, materials, labels, colors, or branding.',evidenceRefs:[...scene.evidenceRefs]}];if(scene.voiceover)assetSlots.push({id:voice,kind:'voiceover',required:true,status:'planned',prompt:scene.voiceover,evidenceRefs:[...scene.evidenceRefs]});
 const layers:ProductionLayer[]=[{id:`${base}-background`,type:'background',zIndex:0,startFrame,endFrame,content:scene.lighting},{id:`${base}-visual-layer`,type:'generated_visual',zIndex:10,startFrame,endFrame,assetSlotId:visual},{id:`${base}-product-layer`,type:'product',zIndex:20,startFrame,endFrame,assetSlotId:product}];if(scene.overlayText)layers.push({id:`${base}-overlay`,type:'overlay_text',zIndex:30,startFrame,endFrame,content:scene.overlayText},{id:`${base}-captions`,type:'captions',zIndex:40,startFrame,endFrame,content:scene.overlayText});if(scene.voiceover)layers.push({id:`${base}-voice-layer`,type:'voiceover',zIndex:50,startFrame,endFrame,assetSlotId:voice,content:scene.voiceover});
 return{id:base,order:sceneIndex+1,startFrame,endFrame,durationFrames,durationSeconds:durationFrames/PRODUCTION_FPS,framing:scene.framing,action:scene.action,cameraMotion:scene.cameraMotion,lighting:scene.lighting,transitionIn:input.transitionIn,transitionOut:input.transitionOut,layers,assetSlots};
}
function compileTarget(board:CreativeStoryboard,targetIndex:number,direction:CreativeDirectionData):ProductionRenderTarget{const dimensions=DIMENSIONS[board.aspectRatio];if(!dimensions)throw new AgentContractError('UNSUPPORTED_PRODUCTION_ASPECT_RATIO',`Production does not support ${board.aspectRatio}. Use 9:16, 16:9, 1:1, or 4:5.`);const durationFrames=board.durationSeconds*PRODUCTION_FPS;let cursor=0;const matchingPrompt=direction.imagePrompts.find((item)=>item.aspectRatio===board.aspectRatio)??direction.imagePrompts[0];const scenes=board.scenes.map((scene,index)=>{const remaining=durationFrames-cursor;const frames=index===board.scenes.length-1?remaining:scene.durationSeconds*PRODUCTION_FPS;if(frames<PRODUCTION_FPS)throw new AgentContractError('INVALID_PRODUCTION_TIMELINE','Every compiled scene must be at least one second.');const compiled=compileScene({scene,sceneIndex:index,targetIndex,startFrame:cursor,durationFrames:frames,negativePrompt:matchingPrompt?.negativePrompt??'Do not alter the product, add unsupported text, logos, claims, watermarks, or unsafe content.',transitionIn:index===0?'cut':direction.videoDirection.transitions[(index-1)%direction.videoDirection.transitions.length],transitionOut:index===board.scenes.length-1?'end':direction.videoDirection.transitions[index%direction.videoDirection.transitions.length]});cursor+=frames;return compiled;});if(cursor!==durationFrames)throw new AgentContractError('INVALID_PRODUCTION_TIMELINE','Compiled scenes must exactly fill the render target.');return{id:`target-${String(targetIndex+1).padStart(2,'0')}`,sourceStoryboardIndex:targetIndex,sourceScriptTitle:board.sourceScriptTitle,platform:board.platform,aspectRatio:board.aspectRatio,width:dimensions.width,height:dimensions.height,fps:PRODUCTION_FPS,durationFrames,durationSeconds:board.durationSeconds,safeArea:dimensions.safeArea,scenes};}
export function buildProductionBlueprint(input:{generatedAt:string;locale:AgentLocale;creativeDirectionId:string;creativeDirectionVersion:number;direction:CreativeDirectionData}):ProductionBlueprint{if(!input.creativeDirectionId||!Number.isSafeInteger(input.creativeDirectionVersion)||input.creativeDirectionVersion<1)throw new AgentContractError('INVALID_PRODUCTION_BLUEPRINT','Creative Direction identity and version are required.');if(!input.direction.storyboards.length)throw new AgentContractError('PRODUCTION_STORYBOARD_REQUIRED','Approved Creative Direction must contain a storyboard.');const targets=input.direction.storyboards.map((board,index)=>compileTarget(board,index,input.direction));const content={schemaVersion:'aurapost.production-blueprint.v1' as const,locale:input.locale,creativeDirectionId:input.creativeDirectionId,creativeDirectionVersion:input.creativeDirectionVersion,renderEngine:'remotion' as const,targets,continuityRules:[...input.direction.videoDirection.continuityRules],transitions:[...input.direction.videoDirection.transitions],audioMood:input.direction.videoDirection.audioMood,captionStyle:input.direction.videoDirection.captionStyle,accessibility:{...input.direction.accessibility},prohibitedAlterations:[...input.direction.productPresentation.prohibitedAlterations],complianceNotes:[...input.direction.complianceNotes],executionPolicy:{mediaGeneration:false as const,rendering:false as const,publishing:false as const,notice:'This blueprint only plans deterministic scene graphs and asset slots. It does not generate media, render video, charge credits, publish, or schedule content.'}};const serialized=JSON.stringify(content);if(Buffer.byteLength(serialized,'utf8')>512*1024)throw new AgentContractError('PRODUCTION_BLUEPRINT_TOO_LARGE','Production Blueprint exceeds 512 KiB.');const contentSha256=crypto.createHash('sha256').update(serialized,'utf8').digest('hex');return{...content,generatedAt:cleanTimestamp(input.generatedAt),contentSha256};}
export function assertProductionBlueprintApprovable(blueprint:ProductionBlueprint):void{if(!blueprint.targets.length||blueprint.targets.some((target)=>!target.scenes.length||target.scenes.some((scene)=>scene.durationFrames<PRODUCTION_FPS||!scene.assetSlots.some((slot)=>slot.kind==='generated_visual'&&slot.required))))throw new AgentContractError('PRODUCTION_BLUEPRINT_INCOMPLETE','Production Blueprint is incomplete.');}
