import assert from 'node:assert/strict';
import test from 'node:test';
import { AgentContractError } from '../../server/agent/contracts.ts';
import { normalizeCampaignContentPackage } from '../../server/agent/campaignContentPackage.ts';

const evidence=[{id:'product_fact:productTitle',field:'productTitle',type:'product_fact',value:'Aura Lamp',source:'Product'}];
const payload={campaignTitle:'Aura Lamp launch',hooks:Array.from({length:4},(_,i)=>({type:'benefit',text:`Hook ${i+1}`,evidenceRefs:[]})),scripts:Array.from({length:2},(_,i)=>({platform:'tiktok',title:`Script ${i+1}`,durationSeconds:20,hook:'See the difference',scenes:Array.from({length:3},(_,j)=>({visual:`Scene ${j+1}`,voiceover:'Product story',onScreenText:'Aura Lamp',evidenceRefs:['product_fact:productTitle']})),cta:'Learn more',evidenceRefs:['product_fact:productTitle']})),ads:Array.from({length:3},(_,i)=>({platform:'instagram',format:'short',headline:`Ad ${i+1}`,primaryText:'Discover Aura Lamp',cta:'Learn more',evidenceRefs:['product_fact:productTitle']})),descriptions:{short:'Discover Aura Lamp',long:'A thoughtful product description for Aura Lamp.',seoTitle:'Aura Lamp',seoDescription:'Explore Aura Lamp.',evidenceRefs:['product_fact:productTitle']},emails:Array.from({length:2},(_,i)=>({type:'launch',subject:`Launch ${i+1}`,body:'Discover Aura Lamp.',evidenceRefs:['product_fact:productTitle']})),landingPage:{headline:'Meet Aura Lamp',subheadline:'Designed for your space',benefits:['Thoughtful design','Simple experience','Clear presentation'],objectionResponses:[{objection:'Is it for me?',response:'Review the product details.'}],faq:Array.from({length:3},(_,i)=>({question:`Question ${i+1}?`,answer:'Review the product details.'})),cta:'Learn more',evidenceRefs:['product_fact:productTitle']},creativePrompts:{images:['Studio product image','Lifestyle product image','Detail product image'],videoConcepts:['Product reveal','Problem and solution']},complianceNotes:['Verify claims before use.']};
test('normalizes a bounded evidence-linked package',()=>{const result=normalizeCampaignContentPackage(payload,evidence);assert.equal(result.hooks.length,4);assert.equal(result.scripts[0].scenes[0].order,1);});
test('rejects unknown evidence references',()=>{const invalid=structuredClone(payload);invalid.ads[0].evidenceRefs=['missing:id'];assert.throws(()=>normalizeCampaignContentPackage(invalid,evidence),AgentContractError);});
test('rejects an ungrounded percentage claim',()=>{const invalid=structuredClone(payload);invalid.ads[0].primaryText='Improve results by 50%';assert.throws(()=>normalizeCampaignContentPackage(invalid,evidence),AgentContractError);});
test('rejects an ungrounded guarantee claim',()=>{const invalid=structuredClone(payload);invalid.ads[0].primaryText='Guaranteed improvement';assert.throws(()=>normalizeCampaignContentPackage(invalid,evidence),AgentContractError);});
test('allows a quantitative claim only when present in evidence',()=>{const supported=[...evidence,{id:'market_evidence:conversion',field:'conversion',type:'market_evidence',value:'Observed 20% conversion rate',source:'Verified source'}];const valid=structuredClone(payload);valid.ads[0].primaryText='Observed 20% conversion rate';valid.ads[0].evidenceRefs=['market_evidence:conversion'];assert.doesNotThrow(()=>normalizeCampaignContentPackage(valid,supported));});
